CREATE DATABASE GESTION_VENTAS;
GO

USE GESTION_VENTAS;
GO


CREATE TABLE FIDE_ESTADO_TB (
    FIDE_ESTADO_ID_PK INT CONSTRAINT FIDE_ESTADO_ID_PK PRIMARY KEY,
    FIDE_ESTADO_TIPO VARCHAR(40)
)
GO


CREATE TABLE FIDE_PAIS_TB (
    FIDE_PAIS_ID_PK INT IDENTITY(1,1),
    FIDE_PAIS_NOMBRE VARCHAR(100),
    FIDE_ESTADO_ID_FK INT,
CONSTRAINT _FIDE_PAIS_ID_PK PRIMARY KEY (FIDE_PAIS_ID_PK),
CONSTRAINT _FIDE_PAIS_ESTADO_ID_FK FOREIGN KEY (FIDE_ESTADO_ID_FK) REFERENCES FIDE_ESTADO_TB(FIDE_ESTADO_ID_PK)
)
GO

CREATE TABLE FIDE_PROVINCIA_TB (
    FIDE_PROVINCIA_ID_PK INT IDENTITY(1,1),
    FIDE_PROVINCIA_NOMBRE VARCHAR(100),
    FIDE_ESTADO_ID_FK INT,
CONSTRAINT _FIDE_PROVINCIA_ID_PK PRIMARY KEY (FIDE_PROVINCIA_ID_PK),
CONSTRAINT _FIDE_PROVINCIA_ESTADO_ID_FK FOREIGN KEY (FIDE_ESTADO_ID_FK) REFERENCES FIDE_ESTADO_TB(FIDE_ESTADO_ID_PK)
)
GO

CREATE TABLE FIDE_CANTON_TB (
    FIDE_CANTON_ID_PK INT IDENTITY(1,1),
    FIDE_CANTON_NOMBRE VARCHAR(100),
    FIDE_ESTADO_ID_FK INT,
CONSTRAINT _FIDE_CANTON_ID_PK PRIMARY KEY (FIDE_CANTON_ID_PK),
CONSTRAINT _FIDE_CANTON_ESTADO_ID_FK FOREIGN KEY (FIDE_ESTADO_ID_FK) REFERENCES FIDE_ESTADO_TB(FIDE_ESTADO_ID_PK)
)
GO

CREATE TABLE FIDE_DISTRITO_TB (
    FIDE_DISTRITO_ID_PK INT IDENTITY(1,1),
    FIDE_DISTRITO_NOMBRE VARCHAR(100),
    FIDE_ESTADO_ID_FK INT,
CONSTRAINT _FIDE_DISTRITO_ID_PK PRIMARY KEY (FIDE_DISTRITO_ID_PK),
CONSTRAINT _FIDE_DISTRITO_ESTADO_ID_FK FOREIGN KEY (FIDE_ESTADO_ID_FK) REFERENCES FIDE_ESTADO_TB(FIDE_ESTADO_ID_PK)
)
GO

CREATE TABLE FIDE_ROLES_TB (
    FIDE_ROLES_ID_PK INT IDENTITY(1,1),
    FIDE_ROLES_NOMBRE VARCHAR(100),
    FIDE_ESTADO_ID_FK INT,
CONSTRAINT _FIDE_ROLES_ID_PK PRIMARY KEY (FIDE_ROLES_ID_PK),
CONSTRAINT _FIDE_ROLES_ESTADO_ID_FK FOREIGN KEY (FIDE_ESTADO_ID_FK) REFERENCES FIDE_ESTADO_TB(FIDE_ESTADO_ID_PK)
)
GO

CREATE TABLE FIDE_USUARIOS_TB (
    FIDE_USUARIOS_ID_PK INT IDENTITY(1,1),
    FIDE_USUARIOS_NOMBRE VARCHAR(100),
    FIDE_USUARIOS_APELLIDO1 VARCHAR(100),
    FIDE_USUARIOS_APELLIDO2 VARCHAR(100),
    FIDE_USUARIOS_RED VARCHAR(100),
    FIDE_USUARIOS_PASS VARCHAR(100),
    FIDE_ROLES_ID_FK INT,
    FIDE_ESTADO_ID_FK INT,
CONSTRAINT _FIDE_USUARIOS_ID_PK PRIMARY KEY (FIDE_USUARIOS_ID_PK, FIDE_ROLES_ID_FK),
CONSTRAINT _FIDE_USUARIOS_ID_UQ UNIQUE (FIDE_USUARIOS_ID_PK),
CONSTRAINT _FIDE_USUARIOS_ROLES_ID_FK FOREIGN KEY (FIDE_ROLES_ID_FK) REFERENCES FIDE_ROLES_TB(FIDE_ROLES_ID_PK),
CONSTRAINT _FIDE_USUARIOS_ESTADO_ID_FK FOREIGN KEY (FIDE_ESTADO_ID_FK) REFERENCES FIDE_ESTADO_TB(FIDE_ESTADO_ID_PK)
)
GO

CREATE TABLE FIDE_EMPRESA_TB (
    FIDE_EMPRESA_CEDULA_PK INT,
    FIDE_EMPRESA_NOMBRE VARCHAR(100),
    FIDE_EMPRESA_TELEFONO VARCHAR(100),
    FIDE_EMPRESA_CORREO VARCHAR(100),
    FIDE_ESTADO_ID_FK INT,
CONSTRAINT _FIDE_EMPRESA_CEDULA_PK PRIMARY KEY (FIDE_EMPRESA_CEDULA_PK),
CONSTRAINT _FIDE_EMPRESA_ESTADO_ID_FK FOREIGN KEY (FIDE_ESTADO_ID_FK) REFERENCES FIDE_ESTADO_TB(FIDE_ESTADO_ID_PK)
)
GO

CREATE TABLE FIDE_CATEGORIAS_TB (
    FIDE_CATEGORIAS_ID_PK INT IDENTITY(1,1),
    FIDE_CATEGORIAS_NOMBRE VARCHAR(100),
    FIDE_CATEGORIAS_DESCRIPCION VARCHAR(100),
    FIDE_ESTADO_ID_FK INT,
CONSTRAINT _FIDE_CATEGORIAS_ID_PK PRIMARY KEY (FIDE_CATEGORIAS_ID_PK),
CONSTRAINT _FIDE_CATEGORIAS_ESTADO_ID_FK FOREIGN KEY (FIDE_ESTADO_ID_FK) REFERENCES FIDE_ESTADO_TB(FIDE_ESTADO_ID_PK)
)
GO

CREATE TABLE FIDE_PRODUCTOS_TB (
    FIDE_PRODUCTOS_ID_PK INT IDENTITY(1,1),
    FIDE_PRODUCTOS_CODIGO INT,
    FIDE_PRODUCTOS_NOMBRE VARCHAR(100),
    FIDE_PRODUCTOS_COSTO DECIMAL(10,2),
    FIDE_PRODUCTOS_DESCRIPCION VARCHAR(100),
    FIDE_CATEGORIAS_ID_FK INT,
    FIDE_ESTADO_ID_FK INT,
    CONSTRAINT _FIDE_PRODUCTOS_ID_PK PRIMARY KEY (FIDE_PRODUCTOS_ID_PK, FIDE_CATEGORIAS_ID_FK),
    CONSTRAINT _FIDE_PRODUCTOS_ID_UQ UNIQUE (FIDE_PRODUCTOS_ID_PK),
    CONSTRAINT _FIDE_PRODUCTOS_CATEGORIAS_ID_FK FOREIGN KEY (FIDE_CATEGORIAS_ID_FK) REFERENCES FIDE_CATEGORIAS_TB(FIDE_CATEGORIAS_ID_PK),
    CONSTRAINT _FIDE_PRODUCTOS_ESTADO_ID_FK FOREIGN KEY (FIDE_ESTADO_ID_FK) REFERENCES FIDE_ESTADO_TB(FIDE_ESTADO_ID_PK)
)
GO

CREATE TABLE FIDE_VENTAS_TB (
    FIDE_VENTAS_ID_PK INT IDENTITY(1,1),
    FIDE_VENTAS_FECHA DATETIME,
    FIDE_USUARIOS_ID_FK INT,
    FIDE_EMPRESA_CEDULA_FK INT,
    FIDE_ESTADO_ID_FK INT,
    CONSTRAINT _FIDE_VENTAS_ID_PK PRIMARY KEY (FIDE_VENTAS_ID_PK, FIDE_USUARIOS_ID_FK),
    CONSTRAINT _FIDE_VENTAS_ID_UQ UNIQUE (FIDE_VENTAS_ID_PK),
    CONSTRAINT _FIDE_VENTAS_USUARIOS_ID_FK FOREIGN KEY (FIDE_USUARIOS_ID_FK) REFERENCES FIDE_USUARIOS_TB(FIDE_USUARIOS_ID_PK),
    CONSTRAINT _FIDE_VENTAS_EMPRESA_CEDULA_FK FOREIGN KEY (FIDE_EMPRESA_CEDULA_FK) REFERENCES FIDE_EMPRESA_TB(FIDE_EMPRESA_CEDULA_PK),
    CONSTRAINT _FIDE_VENTAS_ESTADO_ID_FK FOREIGN KEY (FIDE_ESTADO_ID_FK) REFERENCES FIDE_ESTADO_TB(FIDE_ESTADO_ID_PK)
)
GO

CREATE TABLE FIDE_DETALLE_VENTA_TB (
    FIDE_DETALLE_VENTA_ID_PK INT IDENTITY(1,1),
    FIDE_VENTAS_ID_FK INT,
    FIDE_PRODUCTOS_ID_FK INT,
    FIDE_DETALLE_VENTA_CANTIDAD INT,
    FIDE_ESTADO_ID_FK INT,
    CONSTRAINT _FIDE_DETALLE_VENTA_ID_PK PRIMARY KEY (FIDE_DETALLE_VENTA_ID_PK, FIDE_VENTAS_ID_FK, FIDE_PRODUCTOS_ID_FK),
    CONSTRAINT _FIDE_DETALLE_VENTA_VENTAS_ID_FK FOREIGN KEY (FIDE_VENTAS_ID_FK) REFERENCES FIDE_VENTAS_TB(FIDE_VENTAS_ID_PK),
    CONSTRAINT _FIDE_DETALLE_VENTA_PRODUCTOS_ID_FK FOREIGN KEY (FIDE_PRODUCTOS_ID_FK) REFERENCES FIDE_PRODUCTOS_TB(FIDE_PRODUCTOS_ID_PK),
    CONSTRAINT _FIDE_DETALLE_VENTA_ESTADO_ID_FK FOREIGN KEY (FIDE_ESTADO_ID_FK) REFERENCES FIDE_ESTADO_TB(FIDE_ESTADO_ID_PK)
)
GO

CREATE TABLE FIDE_TIPOS_MOVIMIENTO_TB (
    FIDE_TIPOS_MOVIMIENTO_ID_PK INT IDENTITY(1,1),
    FIDE_TIPOS_MOVIMIENTO_NOMBRE VARCHAR(100),
    FIDE_ESTADO_ID_FK INT,
    CONSTRAINT _FIDE_TIPOS_MOVIMIENTO_ID_PK PRIMARY KEY (FIDE_TIPOS_MOVIMIENTO_ID_PK),
    CONSTRAINT _FIDE_TIPOS_MOVIMIENTO_ESTADO_ID_FK FOREIGN KEY (FIDE_ESTADO_ID_FK) REFERENCES FIDE_ESTADO_TB(FIDE_ESTADO_ID_PK)
)
GO

CREATE TABLE FIDE_MOVIMIENTOS_INVENTARIO_TB (
    FIDE_MOVIMIENTOS_ID_PK INT IDENTITY(1,1),
    FIDE_PRODUCTOS_ID_FK INT,
    FIDE_TIPOS_MOVIMIENTO_ID_FK INT,
    FIDE_MOVIMIENTOS_CANTIDAD INT,
    FIDE_MOVIMIENTOS_FECHA DATETIME,
    FIDE_MOVIMIENTOS_DETALLES VARCHAR(100),
    FIDE_ESTADO_ID_FK INT,
    CONSTRAINT _FIDE_MOVIMIENTOS_INVENTARIO_ID_PK PRIMARY KEY (FIDE_MOVIMIENTOS_ID_PK, FIDE_PRODUCTOS_ID_FK, FIDE_TIPOS_MOVIMIENTO_ID_FK),
    CONSTRAINT _FIDE_MOVIMIENTOS_INVENTARIO_PRODUCTOS_ID_FK FOREIGN KEY (FIDE_PRODUCTOS_ID_FK) REFERENCES FIDE_PRODUCTOS_TB(FIDE_PRODUCTOS_ID_PK),
    CONSTRAINT _FIDE_MOVIMIENTOS_INVENTARIO_TIPOS_MOVIMIENTO_ID_FK FOREIGN KEY (FIDE_TIPOS_MOVIMIENTO_ID_FK) REFERENCES FIDE_TIPOS_MOVIMIENTO_TB(FIDE_TIPOS_MOVIMIENTO_ID_PK),
    CONSTRAINT _FIDE_MOVIMIENTOS_INVENTARIO_ESTADO_ID_FK FOREIGN KEY (FIDE_ESTADO_ID_FK) REFERENCES FIDE_ESTADO_TB(FIDE_ESTADO_ID_PK)
)
GO

CREATE TABLE FIDE_BITACORA_TB (
    FIDE_BITACORA_ID_PK INT IDENTITY(1,1),
    FIDE_USUARIOS_ID_FK INT,
    FIDE_BITACORA_EVENTO VARCHAR(100),
    FIDE_BITACORA_DESCRIPCION VARCHAR(100),
    FIDE_BITACORA_FECHA DATETIME,
    FIDE_ESTADO_ID_FK INT,
    CONSTRAINT _FIDE_BITACORA_ID_PK PRIMARY KEY (FIDE_BITACORA_ID_PK, FIDE_USUARIOS_ID_FK),
    CONSTRAINT _FIDE_BITACORA_USUARIOS_ID_FK FOREIGN KEY (FIDE_USUARIOS_ID_FK) REFERENCES FIDE_USUARIOS_TB(FIDE_USUARIOS_ID_PK),
    CONSTRAINT _FIDE_BITACORA_ESTADO_ID_FK FOREIGN KEY (FIDE_ESTADO_ID_FK) REFERENCES FIDE_ESTADO_TB(FIDE_ESTADO_ID_PK)
)
GO

CREATE TABLE FIDE_DIRECCION_EMPRESA_TB (
    FIDE_EMPRESA_CEDULA_FK INT,
    FIDE_PAIS_ID_FK INT,
    FIDE_PROVINCIA_ID_FK INT,
    FIDE_CANTON_ID_FK INT,
    FIDE_DISTRITO_ID_FK INT,
    FIDE_DIRECCION_OTRAS_SENAS VARCHAR(100),
    FIDE_ESTADO_ID_FK INT,
    CONSTRAINT FIDE_DIRECCION_EMPRESA_ID_PK PRIMARY KEY (FIDE_EMPRESA_CEDULA_FK, FIDE_PAIS_ID_FK, FIDE_PROVINCIA_ID_FK, FIDE_CANTON_ID_FK, FIDE_DISTRITO_ID_FK),
    CONSTRAINT FIDE_DIRECCION_EMPRESA_EMPRESA_FK FOREIGN KEY (FIDE_EMPRESA_CEDULA_FK) REFERENCES FIDE_EMPRESA_TB(FIDE_EMPRESA_CEDULA_PK),
    CONSTRAINT FIDE_DIRECCION_EMPRESA_PAIS_FK FOREIGN KEY (FIDE_PAIS_ID_FK) REFERENCES FIDE_PAIS_TB(FIDE_PAIS_ID_PK),
    CONSTRAINT FIDE_DIRECCION_EMPRESA_PROVINCIA_FK FOREIGN KEY (FIDE_PROVINCIA_ID_FK) REFERENCES FIDE_PROVINCIA_TB(FIDE_PROVINCIA_ID_PK),
    CONSTRAINT FIDE_DIRECCION_EMPRESA_CANTON_FK FOREIGN KEY (FIDE_CANTON_ID_FK) REFERENCES FIDE_CANTON_TB(FIDE_CANTON_ID_PK),
    CONSTRAINT FIDE_DIRECCION_EMPRESA_DISTRITO_FK FOREIGN KEY (FIDE_DISTRITO_ID_FK) REFERENCES FIDE_DISTRITO_TB(FIDE_DISTRITO_ID_PK),
    CONSTRAINT FIDE_DIRECCION_EMPRESA_ESTADO_FK FOREIGN KEY (FIDE_ESTADO_ID_FK) REFERENCES FIDE_ESTADO_TB(FIDE_ESTADO_ID_PK)
)
