CREATE DATABASE GESTION_VENTAS;
GO

USE GESTION_VENTAS;
GO

CREATE TABLE ESTADO (
ID_ESTADO INT CONSTRAINT ID_ESTADO_PK PRIMARY KEY,
TIPO_ESTADO VARCHAR(40)
)
GO

CREATE TABLE PAIS (
ID_PAIS INT CONSTRAINT ID_PAIS_PK PRIMARY KEY IDENTITY(1,1),
NOMBRE_PAIS VARCHAR(100),
ID_ESTADO INT,
CONSTRAINT PAIS_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
)
GO

CREATE TABLE PROVINCIA (
ID_PROVINCIA INT CONSTRAINT ID_PROVINCIA_PK PRIMARY KEY IDENTITY(1,1),
NOMBRE_PROVINCIA VARCHAR(100),
ID_ESTADO INT,
CONSTRAINT PROVINCIA_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
)
GO

CREATE TABLE CANTON (
ID_CANTON INT CONSTRAINT ID_CANTON_PK PRIMARY KEY IDENTITY(1,1),
NOMBRE_CANTON VARCHAR(100),
ID_ESTADO INT,
CONSTRAINT CANTON_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
)
GO

CREATE TABLE DISTRITO (
ID_DISTRITO INT CONSTRAINT ID_DISTRITO_PK PRIMARY KEY IDENTITY(1,1),
NOMBRE_DISTRITO VARCHAR(100),
ID_ESTADO INT,
CONSTRAINT DISTRITO_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
)
GO

CREATE TABLE ROLES (
ID_ROL INT CONSTRAINT ID_ROL_PK PRIMARY KEY IDENTITY(1,1),
ROL_NOMBRE VARCHAR(100),
ID_ESTADO INT,
CONSTRAINT ROL_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
)
GO

CREATE TABLE USUARIOS (
ID_USUARIO INT IDENTITY(1,1),
NOMBRE_USUARIO VARCHAR(100),
APELLIDO_UNO VARCHAR(100),
APELLIDO_DOS VARCHAR(100),
USUARIO_RED VARCHAR(100),
PASS VARCHAR(100),
ID_ROL INT,
ID_ESTADO INT,
CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USUARIO, ID_ROL),
CONSTRAINT UQ_USUARIO_ID UNIQUE (ID_USUARIO),
CONSTRAINT USUARIO_ROL_FK FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL),
CONSTRAINT USUARIO_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
)
GO

CREATE TABLE EMPRESA (
CEDULA_JURIDICA INT CONSTRAINT CEDULA_JURIDICA_PK PRIMARY KEY,
NOMBRE_EMPRESA VARCHAR(100),
TELEFONO_EMPRESA VARCHAR(100),
CORREO_EMPRESA VARCHAR(100),
ID_ESTADO INT,
CONSTRAINT EMPRESA_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
)
GO

CREATE TABLE CATEGORIAS (
ID_CATEGORIA INT CONSTRAINT ID_CATEGORIA_PK PRIMARY KEY IDENTITY(1,1),
NOMBRE_CATEGORIA VARCHAR(100),
DESCRIPCION_CATEGORIA VARCHAR(100),
ID_ESTADO INT,
CONSTRAINT CATEGORIA_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
)
GO

CREATE TABLE PRODUCTOS (
ID_PRODUCTO INT IDENTITY(1,1),
CODIGO_PRODUCTO INT,
NOMBRE_PRODUCTO VARCHAR(100),
COSTO_PRODUCTO DECIMAL(10,2),
DESCRIPCION_PRODUCTO VARCHAR(100),
ID_CATEGORIA INT,
ID_ESTADO INT,
CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO, ID_CATEGORIA),
CONSTRAINT UQ_PRODUCTO_ID UNIQUE (ID_PRODUCTO),
CONSTRAINT PRODUCTO_CATEGORIA_FK FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
CONSTRAINT PRODUCTO_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
)
GO

CREATE TABLE VENTAS (
ID_VENTA INT IDENTITY(1,1),
FECHA_VENTA DATETIME,
ID_USUARIO INT,
CEDULA_JURIDICA INT,
ID_ESTADO INT,
CONSTRAINT PK_VENTA PRIMARY KEY (ID_VENTA,ID_USUARIO),
CONSTRAINT UQ_VENTA_ID UNIQUE (ID_VENTA),
CONSTRAINT VENTAS_USUARIO_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
CONSTRAINT VENTAS_CEDULA_JURIDICA_FK FOREIGN KEY (CEDULA_JURIDICA) REFERENCES EMPRESA(CEDULA_JURIDICA),
CONSTRAINT VENTAS_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
)
GO

CREATE TABLE DETALLE_VENTA (
ID_DETALLE INT IDENTITY(1,1),
ID_VENTA INT,
ID_PRODUCTO INT,
CANTIDAD_VENDIDA INT,
ID_ESTADO INT,
CONSTRAINT DETALLE_VENTA_PK PRIMARY KEY (ID_DETALLE,ID_VENTA,ID_PRODUCTO),
CONSTRAINT DETALLE_VENTA_FK FOREIGN KEY (ID_VENTA) REFERENCES VENTAS(ID_VENTA),
CONSTRAINT DETALLE_PRODUCTO_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
CONSTRAINT DETALLE_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
)
GO

CREATE TABLE TIPOS_MOVIMIENTO (
ID_TIPO_MOVIMIENTO INT CONSTRAINT ID_TIPO_MOVIMIENTO_PK PRIMARY KEY IDENTITY(1,1),
NOMBRE_MOVIMIENTO VARCHAR(100),
ID_ESTADO INT,
CONSTRAINT TIPO_MOVIMIENTO_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
)
GO

CREATE TABLE MOVIMIENTOS_INVENTARIO (
ID_MOVIMIENTO INT IDENTITY(1,1),
ID_PRODUCTO INT,
ID_TIPO_MOVIMIENTO INT,
CANTIDAD_MOVIMIENTO INT,
FECHA_MOVIMIENTO DATETIME,
DETALLES_MOVIMIENTO VARCHAR(100),
ID_ESTADO INT,
CONSTRAINT MOVIMIENTOS_INVENTARIO_PK PRIMARY KEY (ID_MOVIMIENTO,ID_PRODUCTO,ID_TIPO_MOVIMIENTO),
CONSTRAINT MOVIMIENTOS_INVENTARIO_PRODUCTO_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
CONSTRAINT MOVIMIENTOS_INVENTARIO_TIPOS_MOVIMIENTO_FK FOREIGN KEY (ID_TIPO_MOVIMIENTO) REFERENCES TIPOS_MOVIMIENTO(ID_TIPO_MOVIMIENTO),
CONSTRAINT MOVIMIENTOS_INVENTARIO_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
)
GO

CREATE TABLE BITACORA (
ID_BITACORA INT IDENTITY(1,1),
ID_USUARIO INT,
EVENTO_BITACORA VARCHAR(100),
DESCRIPCION_BITACORA VARCHAR(100),
FECHA_BITACORA DATETIME,
ID_ESTADO INT,
CONSTRAINT PK_BITACORA PRIMARY KEY (ID_BITACORA, ID_USUARIO),
CONSTRAINT BITACORA_USUARIO_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
CONSTRAINT BITACORA_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
)
GO

CREATE TABLE DIRECCION_EMPRESA (
CEDULA_JURIDICA INT,
ID_PAIS INT,
ID_PROVINCIA INT,
ID_CANTON INT,
ID_DISTRITO INT,
OTRAS_SENAS VARCHAR(100),
ID_ESTADO INT,
CONSTRAINT DIRECCION_EMPRESA_PK PRIMARY KEY (CEDULA_JURIDICA,ID_PAIS,ID_PROVINCIA,ID_CANTON,ID_DISTRITO),
CONSTRAINT DIRECCION_CEDULA_JURIDICA_FK FOREIGN KEY (CEDULA_JURIDICA) REFERENCES EMPRESA(CEDULA_JURIDICA),
CONSTRAINT DIRECCION_PAIS_FK FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS),
CONSTRAINT DIRECCION_PROVINCIA_FK FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID_PROVINCIA),
CONSTRAINT DIRECCION_CANTON_FK FOREIGN KEY (ID_CANTON) REFERENCES CANTON(ID_CANTON),
CONSTRAINT DIRECCION_DISTRITO_FK FOREIGN KEY (ID_DISTRITO) REFERENCES DISTRITO(ID_DISTRITO),
CONSTRAINT DIRECCION_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
)
