CREATE TABLE FIDE_ACCION_AUDITORIA_TB (
    FIDE_ACCION_AUDITORIA_ID INT PRIMARY KEY,
    FIDE_ACCION_AUDITORIA_NOMBRE VARCHAR(50) NOT NULL
)
GO

-- Inserts para acciones de auditoría att daniel
INSERT INTO FIDE_ACCION_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_ACCION_AUDITORIA_NOMBRE) VALUES (1, 'INSERT');
INSERT INTO FIDE_ACCION_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_ACCION_AUDITORIA_NOMBRE) VALUES (2, 'UPDATE');
INSERT INTO FIDE_ACCION_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_ACCION_AUDITORIA_NOMBRE) VALUES (3, 'DELETE');
GO

CREATE TABLE FIDE_AUDITORIA_TB (
    FIDE_AUDITORIA_ID_PK INT IDENTITY(1,1) PRIMARY KEY,
    FIDE_ACCION_AUDITORIA_ID INT NOT NULL,
    FIDE_AUDITORIA_TABLA VARCHAR(100),
    FIDE_AUDITORIA_FECHA DATETIME DEFAULT GETDATE(),
    FIDE_AUDITORIA_ESTADO INT,
    CONSTRAINT FK_FIDE_AUDITORIA_ACCION FOREIGN KEY (FIDE_ACCION_AUDITORIA_ID) REFERENCES FIDE_ACCION_AUDITORIA_TB(FIDE_ACCION_AUDITORIA_ID)
)
GO
