USE GESTION_VENTAS;
GO

--FUNCIONES
-- OBTENER NOMRBE COMPLETO DE LOS USUARIOS 1
GO
CREATE FUNCTION FIDE_USUARIOS_TB_OBTENER_NOMBRE_COMPLETO_FN (@FIDE_USUARIOS_ID_PK INT)
RETURNS NVARCHAR(100)
AS
BEGIN
    DECLARE @NOMBRE_USUARIO NVARCHAR(100);
    SELECT @NOMBRE_USUARIO = FIDE_USUARIOS_NOMBRE + ' ' + FIDE_USUARIOS_APELLIDO1 + ' ' + FIDE_USUARIOS_APELLIDO2
    FROM FIDE_USUARIOS_TB
    WHERE FIDE_USUARIOS_ID_PK = @FIDE_USUARIOS_ID_PK;
    RETURN @NOMBRE_USUARIO;
END;
SELECT DBO.FIDE_USUARIOS_TB_OBTENER_NOMBRE_COMPLETO_FN(1) AS 'NOMBRE COMPLETO DEL USUARIO SEGUN ID'


-- OBTENER NOMBRE DE UNA EMPRESA POR ID 2
GO
CREATE FUNCTION FIDE_EMPRESA_TB_NOMBRE_POR_ID_FN(@FIDE_EMPRESA_CEDULA_PK INT)
RETURNS NVARCHAR(100)
AS
BEGIN
    DECLARE @FIDE_EMPRESA_NOMBRE NVARCHAR(100);
    SELECT @FIDE_EMPRESA_NOMBRE = FIDE_EMPRESA_NOMBRE
    FROM FIDE_EMPRESA_TB
    WHERE FIDE_EMPRESA_CEDULA_PK = @FIDE_EMPRESA_CEDULA_PK;
    RETURN @FIDE_EMPRESA_NOMBRE;
END;
SELECT DBO.FIDE_EMPRESA_TB_NOMBRE_POR_ID_FN(3101126) AS 'NOMBRE DE LA EMPRESA SEGUN ID';


-- OBTENER NOMBRE DE UNA EMPRESA POR ID 3
GO
CREATE FUNCTION FIDE_ROLES_TB_NOMBRE_ROL_POR_ID_FN(@FIDE_ROLES_ID_PK INT)
RETURNS NVARCHAR(50)
AS
BEGIN
    DECLARE @FIDE_ROLES_NOMBRE  NVARCHAR(50);
    SELECT @FIDE_ROLES_NOMBRE = FIDE_ROLES_NOMBRE
    FROM FIDE_ROLES_TB 
    WHERE FIDE_ROLES_ID_PK = @FIDE_ROLES_ID_PK;
    RETURN @FIDE_ROLES_NOMBRE;
END;
SELECT DBO.FIDE_ROLES_TB_NOMBRE_ROL_POR_ID_FN(1) AS 'NOMBRE DEL ROL SEGUN ID';


--OBTENER CANTIDAD DE PRODUCTOS SEGUN CATEGORIA 4
GO
CREATE FUNCTION FIDE_PRODUCTOS_TB_CANTIDAD_PRODUCTOS_POR_CATEGORIA_FN(@FIDE_CATEGORIAS_ID_FK INT)
RETURNS INT
AS
BEGIN
    DECLARE @TOTAL_PRODUCTOS  INT
    SELECT @TOTAL_PRODUCTOS = COUNT(*)
    FROM FIDE_PRODUCTOS_TB
    WHERE FIDE_CATEGORIAS_ID_FK = @FIDE_CATEGORIAS_ID_FK
    RETURN @TOTAL_PRODUCTOS;
END;
SELECT DBO.FIDE_PRODUCTOS_TB_CANTIDAD_PRODUCTOS_POR_CATEGORIA_FN(4) AS 'TOTAL DE PRODUCTOS SEGUN LA ID DE CATEGORIA';


--OBTENER CANTIDAD DE VENTAS POR CEDULA JURIDICA 5 
GO
CREATE FUNCTION FIDE_VENTAS_TB_CANTIDAD_DE_VENTAS_POR_CEDULA_FN(@FIDE_EMPRESA_CEDULA_FK INT)
RETURNS INT
AS
BEGIN
    DECLARE @TOTAL_VENTAS_EMPRESA INT
    SELECT @TOTAL_VENTAS_EMPRESA = COUNT(*)
    FROM FIDE_VENTAS_TB
    WHERE FIDE_EMPRESA_CEDULA_FK = @FIDE_EMPRESA_CEDULA_FK
    RETURN @TOTAL_VENTAS_EMPRESA;
END;
SELECT DBO.FIDE_VENTAS_TB_CANTIDAD_DE_VENTAS_POR_CEDULA_FN(3101125) AS 'TOTAL DE VENTAS SEGUN LA CEDULA JURIDICA';


--OBTENER CANTIDAD DE MOVIMIENTOS POR FECHA  6
GO
CREATE FUNCTION FIDE_MOVIMIENTOS_INVENTARIO_TB_CANTIDAD_MOVIMIENTOS_POR_PRODUCTO_FN(@FIDE_PRODUCTOS_ID_FK INT)
RETURNS INT
AS
BEGIN
    DECLARE @TOTAL_PRODUCTOS INT
    SELECT @TOTAL_PRODUCTOS = COUNT(*)
    FROM FIDE_MOVIMIENTOS_INVENTARIO_TB
    WHERE FIDE_PRODUCTOS_ID_FK = @FIDE_PRODUCTOS_ID_FK;
    RETURN @TOTAL_PRODUCTOS;
END;
SELECT DBO.FIDE_MOVIMIENTOS_INVENTARIO_TB_CANTIDAD_MOVIMIENTOS_POR_PRODUCTO_FN(3) AS 'TOTAL DE MOVIMIENTOS SEGUN ID DE PRODUCTO';


--OBTENER EVENTOS DE BITACORA POR ID DE USUARIO  7                   
GO
CREATE FUNCTION FIDE_BITACORA_TB_CANTIDAD_EVENTOS_EN_BITACORA_POR_USUARIO_FN(@FIDE_USUARIOS_ID_FK INT)
RETURNS INT
AS
BEGIN
    DECLARE @TOTAL_EVENTOS INT
    SELECT @TOTAL_EVENTOS = COUNT(*)
    FROM FIDE_BITACORA_TB
    WHERE FIDE_USUARIOS_ID_FK = @FIDE_USUARIOS_ID_FK;
    RETURN @TOTAL_EVENTOS;
END;
SELECT DBO.FIDE_BITACORA_TB_CANTIDAD_EVENTOS_EN_BITACORA_POR_USUARIO_FN(2) AS 'TOTAL DE EVENTOS SEGUN ID DE USUARIO';


--OBTENER EL PRECIO DE UN PRODUCTO 8   
GO
CREATE FUNCTION FIDE_PRODUCTOS_TB_PRECIO_PRODUCTO_POR_ID_FN(@FIDE_PRODUCTOS_ID_PK INT)
RETURNS DECIMAL(10,2)
AS
BEGIN
    DECLARE @PRECIO_PRODUCTO DECIMAL(10,2)
    SELECT @PRECIO_PRODUCTO = FIDE_PRODUCTOS_COSTO
    FROM FIDE_PRODUCTOS_TB
    WHERE FIDE_PRODUCTOS_ID_PK = @FIDE_PRODUCTOS_ID_PK;
    RETURN @PRECIO_PRODUCTO;
END;
SELECT DBO.FIDE_PRODUCTOS_TB_PRECIO_PRODUCTO_POR_ID_FN(8) AS 'PRECIO DEL PRODUCTO SEGUN ID';


--OBTENER CUANTAS VENTAS HAY DE UN PRODUCTO 9
GO
CREATE FUNCTION FIDE_DETALLE_VENTA_TB_VENTAS_DE_PRODUCTO_FN(@FIDE_PRODUCTOS_ID_FK INT)
RETURNS INT
AS
BEGIN
    DECLARE @TOTAL_VENDIDO INT
    SELECT @TOTAL_VENDIDO = COUNT(*)
    FROM FIDE_DETALLE_VENTA_TB
    WHERE FIDE_PRODUCTOS_ID_FK = @FIDE_PRODUCTOS_ID_FK;
    RETURN @TOTAL_VENDIDO;
END;
SELECT DBO.FIDE_DETALLE_VENTA_TB_VENTAS_DE_PRODUCTO_FN(2) AS 'VENTAS DEL PRODUCTO SEGUN ID';


--OBTENER CUANTAS DIRECCIONES TIENE UNA EMRPESA 10
CREATE FUNCTION FIDE_DIRECCION_EMPRESA_TB_CONTAR_DIRECCIONES_DE_UNA_EMPRESA_FN(@FIDE_EMPRESA_CEDULA_FK INT)
RETURNS INT
AS
BEGIN
    DECLARE @TOTAL_DIRECCIONES INT;
    SELECT @TOTAL_DIRECCIONES = COUNT(*)
    FROM FIDE_DIRECCION_EMPRESA_TB
    WHERE FIDE_EMPRESA_CEDULA_FK = @FIDE_EMPRESA_CEDULA_FK;
    RETURN @TOTAL_DIRECCIONES;
END;
GO
SELECT DBO.FIDE_DIRECCION_EMPRESA_TB_CONTAR_DIRECCIONES_DE_UNA_EMPRESA_FN(3101124) AS 'TOTAL DIRECCIONES PARA EMPRESA SEGUN CEDULA JURIDICA';
