USE GESTION_VENTAS;
GO

-----------------ESTADO---------------------

SELECT * FROM FIDE_ESTADO_TB;
GO 
-------- INSERTAR ESTADO --------
CREATE PROCEDURE FIDE_ESTADO_INSERTAR_SP
    @FIDE_ESTADO_ID_PK INT,
    @FIDE_ESTADO_TIPO VARCHAR(40)
AS
BEGIN
    IF EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_PK)
    BEGIN
        RAISERROR('EL ID DEL ESTADO YA EXISTE.', 16,1);
        RETURN;
    END;

    INSERT INTO FIDE_ESTADO_TB (FIDE_ESTADO_ID_PK, FIDE_ESTADO_TIPO)
    VALUES (@FIDE_ESTADO_ID_PK, @FIDE_ESTADO_TIPO);
END;
GO

-------- ACTUALIZAR ESTADO --------
CREATE PROCEDURE FIDE_ESTADO_ACTUALIZAR_SP
    @FIDE_ESTADO_ID_PK INT,
    @FIDE_ESTADO_TIPO VARCHAR(40)
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_PK)
    BEGIN
        RAISERROR('EL ESTADO NO EXISTE.', 16,1);
        RETURN;
    END;

    UPDATE FIDE_ESTADO_TB
    SET FIDE_ESTADO_TIPO = @FIDE_ESTADO_TIPO
    WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_PK;
END;
GO

-----------------PAIS---------------------

SELECT * FROM FIDE_PAIS_TB;
GO 

-------- INSERTAR PAIS --------
CREATE PROCEDURE FIDE_PAIS_INSERTAR_SP
    @FIDE_PAIS_NOMBRE VARCHAR(100),
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM FIDE_PAIS_TB WHERE FIDE_PAIS_NOMBRE = @FIDE_PAIS_NOMBRE)
    BEGIN
        RAISERROR('EL NOMBRE DEL PAIS YA EXISTE EN LA TABLA FIDE_PAIS_TB.', 16, 1);
        RETURN;
    END

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    INSERT INTO FIDE_PAIS_TB (FIDE_PAIS_NOMBRE, FIDE_ESTADO_ID_FK)
    VALUES (@FIDE_PAIS_NOMBRE, @FIDE_ESTADO_ID_FK);

END;
GO

-------- ACTUALIZAR PAIS --------
CREATE PROCEDURE FIDE_PAIS_ACTUALIZAR_SP
    @FIDE_PAIS_ID_PK INT,
    @FIDE_PAIS_NOMBRE VARCHAR(100),
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_PAIS_TB WHERE FIDE_PAIS_ID_PK = @FIDE_PAIS_ID_PK)
    BEGIN
        RAISERROR('EL ID_PAIS NO EXISTE EN LA TABLA FIDE_PAIS_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_PAIS_TB
    SET FIDE_PAIS_NOMBRE = @FIDE_PAIS_NOMBRE,
        FIDE_ESTADO_ID_FK = @FIDE_ESTADO_ID_FK
    WHERE FIDE_PAIS_ID_PK = @FIDE_PAIS_ID_PK;

END;
GO

-------- ELIMINAR PAIS --------
CREATE PROCEDURE FIDE_PAIS_ELIMINAR_LOGICO_SP
    @FIDE_PAIS_ID_PK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_PAIS_TB WHERE FIDE_PAIS_ID_PK = @FIDE_PAIS_ID_PK)
    BEGIN
        RAISERROR('EL ID_PAIS NO EXISTE EN LA TABLA FIDE_PAIS_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_PAIS_TB
    SET FIDE_ESTADO_ID_FK = 2
    WHERE FIDE_PAIS_ID_PK = @FIDE_PAIS_ID_PK;

END;
GO

-----------------PROVINCIA---------------------

SELECT * FROM FIDE_PROVINCIA_TB;
GO 

-------- INSERTAR PROVINCIA --------
CREATE PROCEDURE FIDE_PROVINCIA_INSERTAR_SP
    @FIDE_PROVINCIA_NOMBRE VARCHAR(100),
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM FIDE_PROVINCIA_TB WHERE FIDE_PROVINCIA_NOMBRE = @FIDE_PROVINCIA_NOMBRE)
    BEGIN
        RAISERROR('EL NOMBRE DE LA PROVINCIA YA EXISTE EN LA TABLA FIDE_PROVINCIA_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    INSERT INTO FIDE_PROVINCIA_TB (FIDE_PROVINCIA_NOMBRE, FIDE_ESTADO_ID_FK)
    VALUES (@FIDE_PROVINCIA_NOMBRE, @FIDE_ESTADO_ID_FK);

END;
GO

-------- ACTUALIZAR PROVINCIA --------
CREATE PROCEDURE FIDE_PROVINCIA_ACTUALIZAR_SP
    @FIDE_PROVINCIA_ID_PK INT,
    @FIDE_PROVINCIA_NOMBRE VARCHAR(100),
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_PROVINCIA_TB WHERE FIDE_PROVINCIA_ID_PK = @FIDE_PROVINCIA_ID_PK)
    BEGIN
        RAISERROR('EL ID_PROVINCIA NO EXISTE EN LA TABLA FIDE_PROVINCIA_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_PROVINCIA_TB
    SET FIDE_PROVINCIA_NOMBRE = @FIDE_PROVINCIA_NOMBRE,
        FIDE_ESTADO_ID_FK = @FIDE_ESTADO_ID_FK
    WHERE FIDE_PROVINCIA_ID_PK = @FIDE_PROVINCIA_ID_PK;

END;
GO

-------- ELIMINAR PROVINCIA --------
CREATE PROCEDURE FIDE_PROVINCIA_ELIMINAR_LOGICO_SP
    @FIDE_PROVINCIA_ID_PK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_PROVINCIA_TB WHERE FIDE_PROVINCIA_ID_PK = @FIDE_PROVINCIA_ID_PK)
    BEGIN
        RAISERROR('EL ID_PROVINCIA NO EXISTE EN LA TABLA FIDE_PROVINCIA_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_PROVINCIA_TB
    SET FIDE_ESTADO_ID_FK = 2
    WHERE FIDE_PROVINCIA_ID_PK = @FIDE_PROVINCIA_ID_PK;

END;
GO

-----------------CANTON---------------------

SELECT * FROM FIDE_CANTON_TB;
GO 

-------- INSERTAR CANTON --------
CREATE PROCEDURE FIDE_CANTON_INSERTAR_SP
    @FIDE_CANTON_NOMBRE VARCHAR(100),
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM FIDE_CANTON_TB WHERE FIDE_CANTON_NOMBRE = @FIDE_CANTON_NOMBRE)
    BEGIN
        RAISERROR('EL NOMBRE DEL CANTON YA EXISTE EN LA TABLA FIDE_CANTON_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    INSERT INTO FIDE_CANTON_TB (FIDE_CANTON_NOMBRE, FIDE_ESTADO_ID_FK)
    VALUES (@FIDE_CANTON_NOMBRE, @FIDE_ESTADO_ID_FK);

END;
GO

-------- ACTUALIZAR CANTON --------
CREATE PROCEDURE FIDE_CANTON_ACTUALIZAR_SP
    @FIDE_CANTON_ID_PK INT,
    @FIDE_CANTON_NOMBRE VARCHAR(100),
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_CANTON_TB WHERE FIDE_CANTON_ID_PK = @FIDE_CANTON_ID_PK)
    BEGIN
        RAISERROR('EL ID_CANTON NO EXISTE EN LA TABLA FIDE_CANTON_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_CANTON_TB
    SET FIDE_CANTON_NOMBRE = @FIDE_CANTON_NOMBRE,
        FIDE_ESTADO_ID_FK = @FIDE_ESTADO_ID_FK
    WHERE FIDE_CANTON_ID_PK = @FIDE_CANTON_ID_PK;

END;
GO

-------- ELIMINAR CANTON --------
CREATE PROCEDURE FIDE_CANTON_ELIMINAR_LOGICO_SP
    @FIDE_CANTON_ID_PK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_CANTON_TB WHERE FIDE_CANTON_ID_PK = @FIDE_CANTON_ID_PK)
    BEGIN
        RAISERROR('EL ID_CANTON NO EXISTE EN LA TABLA FIDE_CANTON_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_CANTON_TB
    SET FIDE_ESTADO_ID_FK = 2
    WHERE FIDE_CANTON_ID_PK = @FIDE_CANTON_ID_PK;

END;
GO

-----------------DISTRITO---------------------

SELECT * FROM FIDE_DISTRITO_TB;
GO 

-------- INSERTAR DISTRITO --------
CREATE PROCEDURE FIDE_DISTRITO_INSERTAR_SP
    @FIDE_DISTRITO_NOMBRE VARCHAR(100),
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM FIDE_DISTRITO_TB WHERE FIDE_DISTRITO_NOMBRE = @FIDE_DISTRITO_NOMBRE)
    BEGIN
        RAISERROR('EL NOMBRE DEL DISTRITO YA EXISTE EN LA TABLA FIDE_DISTRITO_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    INSERT INTO FIDE_DISTRITO_TB (FIDE_DISTRITO_NOMBRE, FIDE_ESTADO_ID_FK)
    VALUES (@FIDE_DISTRITO_NOMBRE, @FIDE_ESTADO_ID_FK);

END;
GO

-------- ACTUALIZAR DISTRITO --------
CREATE PROCEDURE FIDE_DISTRITO_ACTUALIZAR_SP
    @FIDE_DISTRITO_ID_PK INT,
    @FIDE_DISTRITO_NOMBRE VARCHAR(100),
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_DISTRITO_TB WHERE FIDE_DISTRITO_ID_PK = @FIDE_DISTRITO_ID_PK)
    BEGIN
        RAISERROR('EL ID_DISTRITO NO EXISTE EN LA TABLA FIDE_DISTRITO_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_DISTRITO_TB
    SET FIDE_DISTRITO_NOMBRE = @FIDE_DISTRITO_NOMBRE,
        FIDE_ESTADO_ID_FK = @FIDE_ESTADO_ID_FK
    WHERE FIDE_DISTRITO_ID_PK = @FIDE_DISTRITO_ID_PK;

END;
GO

-------- ELIMINAR DISTRITO --------
CREATE PROCEDURE FIDE_DISTRITO_ELIMINAR_LOGICO_SP
    @FIDE_DISTRITO_ID_PK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_DISTRITO_TB WHERE FIDE_DISTRITO_ID_PK = @FIDE_DISTRITO_ID_PK)
    BEGIN
        RAISERROR('EL ID_DISTRITO NO EXISTE EN LA TABLA FIDE_DISTRITO_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_DISTRITO_TB
    SET FIDE_ESTADO_ID_FK = 2
    WHERE FIDE_DISTRITO_ID_PK = @FIDE_DISTRITO_ID_PK;

END;
GO

-----------------ROLES---------------------

SELECT * FROM FIDE_ROLES_TB;
GO 

-------- INSERTAR ROL --------
CREATE PROCEDURE FIDE_ROL_INSERTAR_SP
    @FIDE_ROLES_NOMBRE VARCHAR(100),
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM FIDE_ROLES_TB WHERE FIDE_ROLES_NOMBRE = @FIDE_ROLES_NOMBRE)
    BEGIN
        RAISERROR('EL NOMBRE DEL ROL YA EXISTE EN LA TABLA FIDE_ROLES_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    INSERT INTO FIDE_ROLES_TB (FIDE_ROLES_NOMBRE, FIDE_ESTADO_ID_FK)
    VALUES (@FIDE_ROLES_NOMBRE, @FIDE_ESTADO_ID_FK);

END;
GO

-------- ACTUALIZAR ROL --------
CREATE PROCEDURE FIDE_ROL_ACTUALIZAR_SP
    @FIDE_ROLES_ID_PK INT,
    @FIDE_ROLES_NOMBRE VARCHAR(100),
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_ROLES_TB WHERE FIDE_ROLES_ID_PK = @FIDE_ROLES_ID_PK)
    BEGIN
        RAISERROR('EL ID_ROL NO EXISTE EN LA TABLA FIDE_ROLES_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_ROLES_TB
    SET FIDE_ROLES_NOMBRE = @FIDE_ROLES_NOMBRE,
        FIDE_ESTADO_ID_FK = @FIDE_ESTADO_ID_FK
    WHERE FIDE_ROLES_ID_PK = @FIDE_ROLES_ID_PK;

END;
GO

-------- ELIMINAR ROL --------
CREATE PROCEDURE FIDE_ROL_ELIMINAR_LOGICO_SP
    @FIDE_ROLES_ID_PK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_ROLES_TB WHERE FIDE_ROLES_ID_PK = @FIDE_ROLES_ID_PK)
    BEGIN
        RAISERROR('EL ID_ROL NO EXISTE EN LA TABLA FIDE_ROLES_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_ROLES_TB
    SET FIDE_ESTADO_ID_FK = 2
    WHERE FIDE_ROLES_ID_PK = @FIDE_ROLES_ID_PK;

END;
GO

-----------------USUARIOS---------------------

SELECT * FROM FIDE_USUARIOS_TB;
GO 

-------- INSERTAR USUARIO --------
CREATE PROCEDURE FIDE_USUARIO_INSERTAR_SP
    @FIDE_USUARIOS_NOMBRE VARCHAR(100),
    @FIDE_USUARIOS_APELLIDO1 VARCHAR(100),
    @FIDE_USUARIOS_APELLIDO2 VARCHAR(100),
    @FIDE_USUARIOS_RED VARCHAR(100),
    @FIDE_USUARIOS_PASS VARCHAR(100),
    @FIDE_ROLES_ID_FK INT,
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM FIDE_USUARIOS_TB WHERE FIDE_USUARIOS_RED = @FIDE_USUARIOS_RED)
    BEGIN
        RAISERROR('EL USUARIO YA EXISTE EN LA TABLA FIDE_USUARIOS_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ROLES_TB WHERE FIDE_ROLES_ID_PK = @FIDE_ROLES_ID_FK)
    BEGIN
        RAISERROR('EL ID_ROL NO EXISTE EN LA TABLA FIDE_ROLES_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    INSERT INTO FIDE_USUARIOS_TB (
        FIDE_USUARIOS_NOMBRE,
        FIDE_USUARIOS_APELLIDO1,
        FIDE_USUARIOS_APELLIDO2,
        FIDE_USUARIOS_RED,
        FIDE_USUARIOS_PASS,
        FIDE_ROLES_ID_FK,
        FIDE_ESTADO_ID_FK
    )
    VALUES (
        @FIDE_USUARIOS_NOMBRE,
        @FIDE_USUARIOS_APELLIDO1,
        @FIDE_USUARIOS_APELLIDO2,
        @FIDE_USUARIOS_RED,
        @FIDE_USUARIOS_PASS,
        @FIDE_ROLES_ID_FK,
        @FIDE_ESTADO_ID_FK
    );

END;
GO

-------- ACTUALIZAR USUARIO --------
CREATE PROCEDURE FIDE_USUARIO_ACTUALIZAR_SP
    @FIDE_USUARIOS_ID_PK INT,
    @FIDE_USUARIOS_NOMBRE VARCHAR(100),
    @FIDE_USUARIOS_APELLIDO1 VARCHAR(100),
    @FIDE_USUARIOS_APELLIDO2 VARCHAR(100),
    @FIDE_USUARIOS_RED VARCHAR(100),
    @FIDE_USUARIOS_PASS VARCHAR(100),
    @FIDE_ROLES_ID_FK INT,
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_USUARIOS_TB WHERE FIDE_USUARIOS_ID_PK = @FIDE_USUARIOS_ID_PK)
    BEGIN
        RAISERROR('EL ID_USUARIO NO EXISTE EN LA TABLA FIDE_USUARIOS_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ROLES_TB WHERE FIDE_ROLES_ID_PK = @FIDE_ROLES_ID_FK)
    BEGIN
        RAISERROR('EL ID_ROL NO EXISTE EN LA TABLA FIDE_ROLES_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_USUARIOS_TB
    SET
        FIDE_USUARIOS_NOMBRE = @FIDE_USUARIOS_NOMBRE,
        FIDE_USUARIOS_APELLIDO1 = @FIDE_USUARIOS_APELLIDO1,
        FIDE_USUARIOS_APELLIDO2 = @FIDE_USUARIOS_APELLIDO2,
        FIDE_USUARIOS_RED = @FIDE_USUARIOS_RED,
        FIDE_USUARIOS_PASS = @FIDE_USUARIOS_PASS,
        FIDE_ROLES_ID_FK = @FIDE_ROLES_ID_FK,
        FIDE_ESTADO_ID_FK = @FIDE_ESTADO_ID_FK
    WHERE FIDE_USUARIOS_ID_PK = @FIDE_USUARIOS_ID_PK;

END;
GO

-------- ELIMINAR USUARIO --------
CREATE PROCEDURE FIDE_USUARIO_ELIMINAR_LOGICO_SP
    @FIDE_USUARIOS_ID_PK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_USUARIOS_TB WHERE FIDE_USUARIOS_ID_PK = @FIDE_USUARIOS_ID_PK)
    BEGIN
        RAISERROR('EL ID_USUARIO NO EXISTE EN LA TABLA FIDE_USUARIOS_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_USUARIOS_TB
    SET FIDE_ESTADO_ID_FK = 2
    WHERE FIDE_USUARIOS_ID_PK = @FIDE_USUARIOS_ID_PK;

END;
GO

-----------------EMPRESA---------------------

SELECT * FROM FIDE_EMPRESA_TB;
GO 

-------- INSERTAR EMPRESA --------
CREATE PROCEDURE FIDE_EMPRESA_INSERTAR_SP
    @FIDE_EMPRESA_CEDULA_PK INT,
    @FIDE_EMPRESA_NOMBRE VARCHAR(100),
    @FIDE_EMPRESA_TELEFONO VARCHAR(100),
    @FIDE_EMPRESA_CORREO VARCHAR(100),
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM FIDE_EMPRESA_TB WHERE FIDE_EMPRESA_CEDULA_PK = @FIDE_EMPRESA_CEDULA_PK)
    BEGIN
        RAISERROR('YA EXISTE UNA EMPRESA CON ESA CÉDULA.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    INSERT INTO FIDE_EMPRESA_TB (
        FIDE_EMPRESA_CEDULA_PK,
        FIDE_EMPRESA_NOMBRE,
        FIDE_EMPRESA_TELEFONO,
        FIDE_EMPRESA_CORREO,
        FIDE_ESTADO_ID_FK
    )
    VALUES (
        @FIDE_EMPRESA_CEDULA_PK,
        @FIDE_EMPRESA_NOMBRE,
        @FIDE_EMPRESA_TELEFONO,
        @FIDE_EMPRESA_CORREO,
        @FIDE_ESTADO_ID_FK
    );

END;
GO

-------- ACTUALIZAR EMPRESA --------
CREATE PROCEDURE FIDE_EMPRESA_ACTUALIZAR_SP
    @FIDE_EMPRESA_CEDULA_PK INT,
    @FIDE_EMPRESA_NOMBRE VARCHAR(100),
    @FIDE_EMPRESA_TELEFONO VARCHAR(100),
    @FIDE_EMPRESA_CORREO VARCHAR(100),
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_EMPRESA_TB WHERE FIDE_EMPRESA_CEDULA_PK = @FIDE_EMPRESA_CEDULA_PK)
    BEGIN
        RAISERROR('LA CÉDULA JURÍDICA NO EXISTE EN LA TABLA FIDE_EMPRESA_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_EMPRESA_TB
    SET FIDE_EMPRESA_NOMBRE = @FIDE_EMPRESA_NOMBRE,
        FIDE_EMPRESA_TELEFONO = @FIDE_EMPRESA_TELEFONO,
        FIDE_EMPRESA_CORREO = @FIDE_EMPRESA_CORREO,
        FIDE_ESTADO_ID_FK = @FIDE_ESTADO_ID_FK
    WHERE FIDE_EMPRESA_CEDULA_PK = @FIDE_EMPRESA_CEDULA_PK;

END;
GO

-------- ELIMINAR EMPRESA --------
CREATE PROCEDURE FIDE_EMPRESA_ELIMINAR_LOGICO_SP
    @FIDE_EMPRESA_CEDULA_PK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_EMPRESA_TB WHERE FIDE_EMPRESA_CEDULA_PK = @FIDE_EMPRESA_CEDULA_PK)
    BEGIN
        RAISERROR('LA CÉDULA JURÍDICA NO EXISTE EN LA TABLA FIDE_EMPRESA_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_EMPRESA_TB
    SET FIDE_ESTADO_ID_FK = 2
    WHERE FIDE_EMPRESA_CEDULA_PK = @FIDE_EMPRESA_CEDULA_PK;

END;
GO

-----------------CATEGORIAS---------------------

SELECT * FROM FIDE_CATEGORIAS_TB;
GO 

-------- INSERTAR CATEGORIA --------
CREATE PROCEDURE FIDE_CATEGORIA_INSERTAR_SP
    @FIDE_CATEGORIAS_NOMBRE VARCHAR(100),
    @FIDE_CATEGORIAS_DESCRIPCION VARCHAR(100),
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM FIDE_CATEGORIAS_TB WHERE FIDE_CATEGORIAS_NOMBRE = @FIDE_CATEGORIAS_NOMBRE)
    BEGIN
        RAISERROR('YA EXISTE UNA CATEGORÍA CON ESE NOMBRE EN LA TABLA FIDE_CATEGORIAS_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    INSERT INTO FIDE_CATEGORIAS_TB (
        FIDE_CATEGORIAS_NOMBRE,
        FIDE_CATEGORIAS_DESCRIPCION,
        FIDE_ESTADO_ID_FK
    )
    VALUES (
        @FIDE_CATEGORIAS_NOMBRE,
        @FIDE_CATEGORIAS_DESCRIPCION,
        @FIDE_ESTADO_ID_FK
    );

END;
GO

-------- ACTUALIZAR CATEGORIA --------
CREATE PROCEDURE FIDE_CATEGORIA_ACTUALIZAR_SP
    @FIDE_CATEGORIAS_ID_PK INT,
    @FIDE_CATEGORIAS_NOMBRE VARCHAR(100),
    @FIDE_CATEGORIAS_DESCRIPCION VARCHAR(100),
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_CATEGORIAS_TB WHERE FIDE_CATEGORIAS_ID_PK = @FIDE_CATEGORIAS_ID_PK)
    BEGIN
        RAISERROR('EL ID_CATEGORIA NO EXISTE EN LA TABLA FIDE_CATEGORIAS_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_CATEGORIAS_TB
    SET FIDE_CATEGORIAS_NOMBRE = @FIDE_CATEGORIAS_NOMBRE,
        FIDE_CATEGORIAS_DESCRIPCION = @FIDE_CATEGORIAS_DESCRIPCION,
        FIDE_ESTADO_ID_FK = @FIDE_ESTADO_ID_FK
    WHERE FIDE_CATEGORIAS_ID_PK = @FIDE_CATEGORIAS_ID_PK;

END;
GO

-------- ELIMINAR CATEGORIA --------
CREATE PROCEDURE FIDE_CATEGORIA_ELIMINAR_LOGICO_SP
    @FIDE_CATEGORIAS_ID_PK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_CATEGORIAS_TB WHERE FIDE_CATEGORIAS_ID_PK = @FIDE_CATEGORIAS_ID_PK)
    BEGIN
        RAISERROR('EL ID_CATEGORIA NO EXISTE EN LA TABLA FIDE_CATEGORIAS_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_CATEGORIAS_TB
    SET FIDE_ESTADO_ID_FK = 2
    WHERE FIDE_CATEGORIAS_ID_PK = @FIDE_CATEGORIAS_ID_PK;

END;
GO

-----------------PRODUCTOS---------------------

SELECT * FROM FIDE_PRODUCTOS_TB;
GO 

-------- INSERTAR PRODUCTO --------
CREATE PROCEDURE FIDE_PRODUCTO_INSERTAR_SP
    @FIDE_PRODUCTOS_CODIGO INT,
    @FIDE_PRODUCTOS_NOMBRE VARCHAR(100),
    @FIDE_PRODUCTOS_COSTO DECIMAL(10,2),
    @FIDE_PRODUCTOS_DESCRIPCION VARCHAR(100),
    @FIDE_CATEGORIAS_ID_FK INT,
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM FIDE_PRODUCTOS_TB WHERE FIDE_PRODUCTOS_CODIGO = @FIDE_PRODUCTOS_CODIGO)
    BEGIN
        RAISERROR('YA EXISTE UN PRODUCTO CON ESE CÓDIGO EN LA TABLA FIDE_PRODUCTOS_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_CATEGORIAS_TB WHERE FIDE_CATEGORIAS_ID_PK = @FIDE_CATEGORIAS_ID_FK)
    BEGIN
        RAISERROR('EL ID_CATEGORIA NO EXISTE EN LA TABLA FIDE_CATEGORIAS_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    INSERT INTO FIDE_PRODUCTOS_TB (
        FIDE_PRODUCTOS_CODIGO,
        FIDE_PRODUCTOS_NOMBRE,
        FIDE_PRODUCTOS_COSTO,
        FIDE_PRODUCTOS_DESCRIPCION,
        FIDE_CATEGORIAS_ID_FK,
        FIDE_ESTADO_ID_FK
    )
    VALUES (
        @FIDE_PRODUCTOS_CODIGO,
        @FIDE_PRODUCTOS_NOMBRE,
        @FIDE_PRODUCTOS_COSTO,
        @FIDE_PRODUCTOS_DESCRIPCION,
        @FIDE_CATEGORIAS_ID_FK,
        @FIDE_ESTADO_ID_FK
    );

END;
GO

-------- ACTUALIZAR PRODUCTO --------
CREATE PROCEDURE FIDE_PRODUCTO_ACTUALIZAR_SP
    @FIDE_PRODUCTOS_ID_PK INT,
    @FIDE_PRODUCTOS_CODIGO INT,
    @FIDE_PRODUCTOS_NOMBRE VARCHAR(100),
    @FIDE_PRODUCTOS_COSTO DECIMAL(10,2),
    @FIDE_PRODUCTOS_DESCRIPCION VARCHAR(100),
    @FIDE_CATEGORIAS_ID_FK INT,
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_PRODUCTOS_TB WHERE FIDE_PRODUCTOS_ID_PK = @FIDE_PRODUCTOS_ID_PK)
    BEGIN
        RAISERROR('EL ID_PRODUCTO NO EXISTE EN LA TABLA FIDE_PRODUCTOS_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_CATEGORIAS_TB WHERE FIDE_CATEGORIAS_ID_PK = @FIDE_CATEGORIAS_ID_FK)
    BEGIN
        RAISERROR('EL ID_CATEGORIA NO EXISTE EN LA TABLA FIDE_CATEGORIAS_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_PRODUCTOS_TB
    SET FIDE_PRODUCTOS_CODIGO = @FIDE_PRODUCTOS_CODIGO,
        FIDE_PRODUCTOS_NOMBRE = @FIDE_PRODUCTOS_NOMBRE,
        FIDE_PRODUCTOS_COSTO = @FIDE_PRODUCTOS_COSTO,
        FIDE_PRODUCTOS_DESCRIPCION = @FIDE_PRODUCTOS_DESCRIPCION,
        FIDE_CATEGORIAS_ID_FK = @FIDE_CATEGORIAS_ID_FK,
        FIDE_ESTADO_ID_FK = @FIDE_ESTADO_ID_FK
    WHERE FIDE_PRODUCTOS_ID_PK = @FIDE_PRODUCTOS_ID_PK;

END;
GO

-------- ELIMINAR PRODUCTO --------
CREATE PROCEDURE FIDE_PRODUCTO_ELIMINAR_LOGICO_SP
    @FIDE_PRODUCTOS_ID_PK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_PRODUCTOS_TB WHERE FIDE_PRODUCTOS_ID_PK = @FIDE_PRODUCTOS_ID_PK)
    BEGIN
        RAISERROR('EL ID_PRODUCTO NO EXISTE EN LA TABLA FIDE_PRODUCTOS_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_PRODUCTOS_TB
    SET FIDE_ESTADO_ID_FK = 2
    WHERE FIDE_PRODUCTOS_ID_PK = @FIDE_PRODUCTOS_ID_PK;

END;
GO

-----------------VENTAS---------------------

SELECT * FROM FIDE_VENTAS_TB;
GO 

-------- INSERTAR VENTA --------
CREATE PROCEDURE FIDE_VENTA_INSERTAR_SP
    @FIDE_VENTAS_FECHA DATETIME,
    @FIDE_USUARIOS_ID_FK INT,
    @FIDE_EMPRESA_CEDULA_FK INT,
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_USUARIOS_TB WHERE FIDE_USUARIOS_ID_PK = @FIDE_USUARIOS_ID_FK)
    BEGIN
        RAISERROR('EL ID_USUARIO NO EXISTE EN LA TABLA FIDE_USUARIOS_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_EMPRESA_TB WHERE FIDE_EMPRESA_CEDULA_PK = @FIDE_EMPRESA_CEDULA_FK)
    BEGIN
        RAISERROR('LA CÉDULA JURÍDICA NO EXISTE EN LA TABLA FIDE_EMPRESA_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    INSERT INTO FIDE_VENTAS_TB (
        FIDE_VENTAS_FECHA,
        FIDE_USUARIOS_ID_FK,
        FIDE_EMPRESA_CEDULA_FK,
        FIDE_ESTADO_ID_FK
    )
    VALUES (
        @FIDE_VENTAS_FECHA,
        @FIDE_USUARIOS_ID_FK,
        @FIDE_EMPRESA_CEDULA_FK,
        @FIDE_ESTADO_ID_FK
    );

END;
GO

-------- ACTUALIZAR VENTA --------
CREATE PROCEDURE FIDE_VENTA_ACTUALIZAR_SP
    @FIDE_VENTAS_ID_PK INT,
    @FIDE_VENTAS_FECHA DATETIME,
    @FIDE_USUARIOS_ID_FK INT,
    @FIDE_EMPRESA_CEDULA_FK INT,
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_VENTAS_TB WHERE FIDE_VENTAS_ID_PK = @FIDE_VENTAS_ID_PK)
    BEGIN
        RAISERROR('EL ID_VENTA NO EXISTE EN LA TABLA FIDE_VENTAS_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_USUARIOS_TB WHERE FIDE_USUARIOS_ID_PK = @FIDE_USUARIOS_ID_FK)
    BEGIN
        RAISERROR('EL ID_USUARIO NO EXISTE EN LA TABLA FIDE_USUARIOS_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_EMPRESA_TB WHERE FIDE_EMPRESA_CEDULA_PK = @FIDE_EMPRESA_CEDULA_FK)
    BEGIN
        RAISERROR('LA CÉDULA JURÍDICA NO EXISTE EN LA TABLA FIDE_EMPRESA_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_VENTAS_TB
    SET FIDE_VENTAS_FECHA = @FIDE_VENTAS_FECHA,
        FIDE_USUARIOS_ID_FK = @FIDE_USUARIOS_ID_FK,
        FIDE_EMPRESA_CEDULA_FK = @FIDE_EMPRESA_CEDULA_FK,
        FIDE_ESTADO_ID_FK = @FIDE_ESTADO_ID_FK
    WHERE FIDE_VENTAS_ID_PK = @FIDE_VENTAS_ID_PK;

END;
GO

-------- ELIMINAR VENTA --------
CREATE PROCEDURE FIDE_VENTA_ELIMINAR_LOGICO_SP
    @FIDE_VENTAS_ID_PK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_VENTAS_TB WHERE FIDE_VENTAS_ID_PK = @FIDE_VENTAS_ID_PK)
    BEGIN
        RAISERROR('EL ID_VENTA NO EXISTE EN LA TABLA FIDE_VENTAS_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_VENTAS_TB
    SET FIDE_ESTADO_ID_FK = 2
    WHERE FIDE_VENTAS_ID_PK = @FIDE_VENTAS_ID_PK;

END;
GO

-----------------DETALLE_VENTA---------------------

SELECT * FROM FIDE_DETALLE_VENTA_TB;
GO 

-------- INSERTAR DETALLE VENTA --------
CREATE PROCEDURE FIDE_DETALLE_VENTA_INSERTAR_SP
    @FIDE_VENTAS_ID_FK INT,
    @FIDE_PRODUCTOS_ID_FK INT,
    @FIDE_DETALLE_VENTA_CANTIDAD INT,
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_VENTAS_TB WHERE FIDE_VENTAS_ID_PK = @FIDE_VENTAS_ID_FK)
    BEGIN
        RAISERROR('EL ID_VENTA NO EXISTE EN LA TABLA FIDE_VENTAS_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_PRODUCTOS_TB WHERE FIDE_PRODUCTOS_ID_PK = @FIDE_PRODUCTOS_ID_FK)
    BEGIN
        RAISERROR('EL ID_PRODUCTO NO EXISTE EN LA TABLA FIDE_PRODUCTOS_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    INSERT INTO FIDE_DETALLE_VENTA_TB (
        FIDE_VENTAS_ID_FK,
        FIDE_PRODUCTOS_ID_FK,
        FIDE_DETALLE_VENTA_CANTIDAD,
        FIDE_ESTADO_ID_FK
    )
    VALUES (
        @FIDE_VENTAS_ID_FK,
        @FIDE_PRODUCTOS_ID_FK,
        @FIDE_DETALLE_VENTA_CANTIDAD,
        @FIDE_ESTADO_ID_FK
    );

END;
GO

-------- ACTUALIZAR DETALLE VENTA --------
CREATE PROCEDURE FIDE_DETALLE_VENTA_ACTUALIZAR_SP
    @FIDE_DETALLE_VENTA_ID_PK INT,
    @FIDE_VENTAS_ID_FK INT,
    @FIDE_PRODUCTOS_ID_FK INT,
    @FIDE_DETALLE_VENTA_CANTIDAD INT,
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM FIDE_DETALLE_VENTA_TB 
        WHERE FIDE_DETALLE_VENTA_ID_PK = @FIDE_DETALLE_VENTA_ID_PK 
          AND FIDE_VENTAS_ID_FK = @FIDE_VENTAS_ID_FK 
          AND FIDE_PRODUCTOS_ID_FK = @FIDE_PRODUCTOS_ID_FK
    )
    BEGIN
        RAISERROR('EL DETALLE DE VENTA NO EXISTE EN LA TABLA FIDE_DETALLE_VENTA_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_VENTAS_TB WHERE FIDE_VENTAS_ID_PK = @FIDE_VENTAS_ID_FK)
    BEGIN
        RAISERROR('EL ID_VENTA NO EXISTE EN LA TABLA FIDE_VENTAS_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_PRODUCTOS_TB WHERE FIDE_PRODUCTOS_ID_PK = @FIDE_PRODUCTOS_ID_FK)
    BEGIN
        RAISERROR('EL ID_PRODUCTO NO EXISTE EN LA TABLA FIDE_PRODUCTOS_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_DETALLE_VENTA_TB
    SET FIDE_DETALLE_VENTA_CANTIDAD = @FIDE_DETALLE_VENTA_CANTIDAD,
        FIDE_ESTADO_ID_FK = @FIDE_ESTADO_ID_FK
    WHERE FIDE_DETALLE_VENTA_ID_PK = @FIDE_DETALLE_VENTA_ID_PK
      AND FIDE_VENTAS_ID_FK = @FIDE_VENTAS_ID_FK
      AND FIDE_PRODUCTOS_ID_FK = @FIDE_PRODUCTOS_ID_FK;

END;
GO

-------- ELIMINAR DETALLE VENTA --------
CREATE PROCEDURE FIDE_DETALLE_VENTA_ELIMINAR_LOGICO_SP
    @FIDE_DETALLE_VENTA_ID_PK INT,
    @FIDE_VENTAS_ID_FK INT,
    @FIDE_PRODUCTOS_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM FIDE_DETALLE_VENTA_TB 
        WHERE FIDE_DETALLE_VENTA_ID_PK = @FIDE_DETALLE_VENTA_ID_PK 
          AND FIDE_VENTAS_ID_FK = @FIDE_VENTAS_ID_FK 
          AND FIDE_PRODUCTOS_ID_FK = @FIDE_PRODUCTOS_ID_FK
    )
    BEGIN
        RAISERROR('EL DETALLE DE VENTA NO EXISTE EN LA TABLA FIDE_DETALLE_VENTA_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_DETALLE_VENTA_TB
    SET FIDE_ESTADO_ID_FK = 2
    WHERE FIDE_DETALLE_VENTA_ID_PK = @FIDE_DETALLE_VENTA_ID_PK
      AND FIDE_VENTAS_ID_FK = @FIDE_VENTAS_ID_FK
      AND FIDE_PRODUCTOS_ID_FK = @FIDE_PRODUCTOS_ID_FK;

END;
GO

-----------------TIPOS_MOVIMIENTO---------------------

SELECT * FROM FIDE_TIPOS_MOVIMIENTO_TB;
GO 

-------- INSERTAR TIPO MOVIMIENTO --------
CREATE PROCEDURE FIDE_TIPO_MOVIMIENTO_INSERTAR_SP
    @FIDE_TIPOS_MOVIMIENTO_NOMBRE VARCHAR(100),
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM FIDE_TIPOS_MOVIMIENTO_TB WHERE FIDE_TIPOS_MOVIMIENTO_NOMBRE = @FIDE_TIPOS_MOVIMIENTO_NOMBRE)
    BEGIN
        RAISERROR('EL NOMBRE DEL TIPO DE MOVIMIENTO YA EXISTE EN LA TABLA FIDE_TIPOS_MOVIMIENTO_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    INSERT INTO FIDE_TIPOS_MOVIMIENTO_TB (FIDE_TIPOS_MOVIMIENTO_NOMBRE, FIDE_ESTADO_ID_FK)
    VALUES (@FIDE_TIPOS_MOVIMIENTO_NOMBRE, @FIDE_ESTADO_ID_FK);

END;
GO

-------- ACTUALIZAR TIPO MOVIMIENTO --------
CREATE PROCEDURE FIDE_TIPO_MOVIMIENTO_ACTUALIZAR_SP
    @FIDE_TIPOS_MOVIMIENTO_ID_PK INT,
    @FIDE_TIPOS_MOVIMIENTO_NOMBRE VARCHAR(100),
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_TIPOS_MOVIMIENTO_TB WHERE FIDE_TIPOS_MOVIMIENTO_ID_PK = @FIDE_TIPOS_MOVIMIENTO_ID_PK)
    BEGIN
        RAISERROR('EL ID_TIPO_MOVIMIENTO NO EXISTE EN LA TABLA FIDE_TIPOS_MOVIMIENTO_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_TIPOS_MOVIMIENTO_TB
    SET FIDE_TIPOS_MOVIMIENTO_NOMBRE = @FIDE_TIPOS_MOVIMIENTO_NOMBRE,
        FIDE_ESTADO_ID_FK = @FIDE_ESTADO_ID_FK
    WHERE FIDE_TIPOS_MOVIMIENTO_ID_PK = @FIDE_TIPOS_MOVIMIENTO_ID_PK;

END;
GO

-------- ELIMINAR TIPO MOVIMIENTO --------
CREATE PROCEDURE FIDE_TIPO_MOVIMIENTO_ELIMINAR_LOGICO_SP
    @FIDE_TIPOS_MOVIMIENTO_ID_PK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_TIPOS_MOVIMIENTO_TB WHERE FIDE_TIPOS_MOVIMIENTO_ID_PK = @FIDE_TIPOS_MOVIMIENTO_ID_PK)
    BEGIN
        RAISERROR('EL ID_TIPO_MOVIMIENTO NO EXISTE EN LA TABLA FIDE_TIPOS_MOVIMIENTO_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_TIPOS_MOVIMIENTO_TB
    SET FIDE_ESTADO_ID_FK = 2
    WHERE FIDE_TIPOS_MOVIMIENTO_ID_PK = @FIDE_TIPOS_MOVIMIENTO_ID_PK;

END;
GO

-----------------MOVIMIENTOS_INVENTARIO---------------------

SELECT * FROM FIDE_MOVIMIENTOS_INVENTARIO_TB;
GO 

-------- INSERTAR MOVIMIENTO INVENTARIO --------
CREATE PROCEDURE FIDE_MOVIMIENTO_INVENTARIO_INSERTAR_SP
    @FIDE_PRODUCTOS_ID_FK INT,
    @FIDE_TIPOS_MOVIMIENTO_ID_FK INT,
    @FIDE_MOVIMIENTOS_CANTIDAD INT,
    @FIDE_MOVIMIENTOS_FECHA DATETIME,
    @FIDE_MOVIMIENTOS_DETALLES VARCHAR(100),
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_PRODUCTOS_TB WHERE FIDE_PRODUCTOS_ID_PK = @FIDE_PRODUCTOS_ID_FK)
    BEGIN
        RAISERROR('EL ID_PRODUCTO NO EXISTE EN LA TABLA FIDE_PRODUCTOS_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_TIPOS_MOVIMIENTO_TB WHERE FIDE_TIPOS_MOVIMIENTO_ID_PK = @FIDE_TIPOS_MOVIMIENTO_ID_FK)
    BEGIN
        RAISERROR('EL ID_TIPO_MOVIMIENTO NO EXISTE EN LA TABLA FIDE_TIPOS_MOVIMIENTO_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    INSERT INTO FIDE_MOVIMIENTOS_INVENTARIO_TB (
        FIDE_PRODUCTOS_ID_FK,
        FIDE_TIPOS_MOVIMIENTO_ID_FK,
        FIDE_MOVIMIENTOS_CANTIDAD,
        FIDE_MOVIMIENTOS_FECHA,
        FIDE_MOVIMIENTOS_DETALLES,
        FIDE_ESTADO_ID_FK
    )
    VALUES (
        @FIDE_PRODUCTOS_ID_FK,
        @FIDE_TIPOS_MOVIMIENTO_ID_FK,
        @FIDE_MOVIMIENTOS_CANTIDAD,
        @FIDE_MOVIMIENTOS_FECHA,
        @FIDE_MOVIMIENTOS_DETALLES,
        @FIDE_ESTADO_ID_FK
    );

END;
GO

-------- ACTUALIZAR MOVIMIENTO INVENTARIO --------
CREATE PROCEDURE FIDE_MOVIMIENTO_INVENTARIO_ACTUALIZAR_SP
    @FIDE_MOVIMIENTOS_ID_PK INT,
    @FIDE_PRODUCTOS_ID_FK INT,
    @FIDE_TIPOS_MOVIMIENTO_ID_FK INT,
    @FIDE_MOVIMIENTOS_CANTIDAD INT,
    @FIDE_MOVIMIENTOS_FECHA DATETIME,
    @FIDE_MOVIMIENTOS_DETALLES VARCHAR(100),
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM FIDE_MOVIMIENTOS_INVENTARIO_TB
        WHERE FIDE_MOVIMIENTOS_ID_PK = @FIDE_MOVIMIENTOS_ID_PK
          AND FIDE_PRODUCTOS_ID_FK = @FIDE_PRODUCTOS_ID_FK
          AND FIDE_TIPOS_MOVIMIENTO_ID_FK = @FIDE_TIPOS_MOVIMIENTO_ID_FK
    )
    BEGIN
        RAISERROR('EL MOVIMIENTO NO EXISTE EN LA TABLA FIDE_MOVIMIENTOS_INVENTARIO_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_PRODUCTOS_TB WHERE FIDE_PRODUCTOS_ID_PK = @FIDE_PRODUCTOS_ID_FK)
    BEGIN
        RAISERROR('EL ID_PRODUCTO NO EXISTE EN LA TABLA FIDE_PRODUCTOS_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_TIPOS_MOVIMIENTO_TB WHERE FIDE_TIPOS_MOVIMIENTO_ID_PK = @FIDE_TIPOS_MOVIMIENTO_ID_FK)
    BEGIN
        RAISERROR('EL ID_TIPO_MOVIMIENTO NO EXISTE EN LA TABLA FIDE_TIPOS_MOVIMIENTO_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_MOVIMIENTOS_INVENTARIO_TB
    SET FIDE_MOVIMIENTOS_CANTIDAD = @FIDE_MOVIMIENTOS_CANTIDAD,
        FIDE_MOVIMIENTOS_FECHA = @FIDE_MOVIMIENTOS_FECHA,
        FIDE_MOVIMIENTOS_DETALLES = @FIDE_MOVIMIENTOS_DETALLES,
        FIDE_ESTADO_ID_FK = @FIDE_ESTADO_ID_FK
    WHERE FIDE_MOVIMIENTOS_ID_PK = @FIDE_MOVIMIENTOS_ID_PK
      AND FIDE_PRODUCTOS_ID_FK = @FIDE_PRODUCTOS_ID_FK
      AND FIDE_TIPOS_MOVIMIENTO_ID_FK = @FIDE_TIPOS_MOVIMIENTO_ID_FK;

END;
GO

-------- ELIMINAR MOVIMIENTO INVENTARIO --------
CREATE PROCEDURE FIDE_MOVIMIENTO_INVENTARIO_ELIMINAR_LOGICO_SP
    @FIDE_MOVIMIENTOS_ID_PK INT,
    @FIDE_PRODUCTOS_ID_FK INT,
    @FIDE_TIPOS_MOVIMIENTO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM FIDE_MOVIMIENTOS_INVENTARIO_TB
        WHERE FIDE_MOVIMIENTOS_ID_PK = @FIDE_MOVIMIENTOS_ID_PK
          AND FIDE_PRODUCTOS_ID_FK = @FIDE_PRODUCTOS_ID_FK
          AND FIDE_TIPOS_MOVIMIENTO_ID_FK = @FIDE_TIPOS_MOVIMIENTO_ID_FK
    )
    BEGIN
        RAISERROR('EL MOVIMIENTO NO EXISTE EN LA TABLA FIDE_MOVIMIENTOS_INVENTARIO_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_MOVIMIENTOS_INVENTARIO_TB
    SET FIDE_ESTADO_ID_FK = 2
    WHERE FIDE_MOVIMIENTOS_ID_PK = @FIDE_MOVIMIENTOS_ID_PK
      AND FIDE_PRODUCTOS_ID_FK = @FIDE_PRODUCTOS_ID_FK
      AND FIDE_TIPOS_MOVIMIENTO_ID_FK = @FIDE_TIPOS_MOVIMIENTO_ID_FK;

END;
GO

-----------------BITACORA---------------------

SELECT * FROM FIDE_BITACORA_TB;
GO 

-------- INSERTAR EVENTO BITÁCORA --------
CREATE PROCEDURE FIDE_BITACORA_INSERTAR_SP
    @FIDE_USUARIOS_ID_FK INT,
    @FIDE_BITACORA_EVENTO VARCHAR(100),
    @FIDE_BITACORA_DESCRIPCION VARCHAR(100),
    @FIDE_BITACORA_FECHA DATETIME,
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM FIDE_USUARIOS_TB WHERE FIDE_USUARIOS_ID_PK = @FIDE_USUARIOS_ID_FK)
    BEGIN
        RAISERROR('EL ID_USUARIO NO EXISTE EN LA TABLA FIDE_USUARIOS_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    INSERT INTO FIDE_BITACORA_TB (
        FIDE_USUARIOS_ID_FK,
        FIDE_BITACORA_EVENTO,
        FIDE_BITACORA_DESCRIPCION,
        FIDE_BITACORA_FECHA,
        FIDE_ESTADO_ID_FK
    )
    VALUES (
        @FIDE_USUARIOS_ID_FK,
        @FIDE_BITACORA_EVENTO,
        @FIDE_BITACORA_DESCRIPCION,
        @FIDE_BITACORA_FECHA,
        @FIDE_ESTADO_ID_FK
    );

END;
GO

-------- ACTUALIZAR EVENTO BITÁCORA --------
CREATE PROCEDURE FIDE_BITACORA_ACTUALIZAR_SP
    @FIDE_BITACORA_ID_PK INT,
    @FIDE_USUARIOS_ID_FK INT,
    @FIDE_BITACORA_EVENTO VARCHAR(100),
    @FIDE_BITACORA_DESCRIPCION VARCHAR(100),
    @FIDE_BITACORA_FECHA DATETIME,
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM FIDE_BITACORA_TB 
        WHERE FIDE_BITACORA_ID_PK = @FIDE_BITACORA_ID_PK
          AND FIDE_USUARIOS_ID_FK = @FIDE_USUARIOS_ID_FK
    )
    BEGIN
        RAISERROR('EL EVENTO DE BITÁCORA NO EXISTE EN LA TABLA FIDE_BITACORA_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_USUARIOS_TB WHERE FIDE_USUARIOS_ID_PK = @FIDE_USUARIOS_ID_FK)
    BEGIN
        RAISERROR('EL ID_USUARIO NO EXISTE EN LA TABLA FIDE_USUARIOS_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA FIDE_ESTADO_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_BITACORA_TB
    SET FIDE_BITACORA_EVENTO = @FIDE_BITACORA_EVENTO,
        FIDE_BITACORA_DESCRIPCION = @FIDE_BITACORA_DESCRIPCION,
        FIDE_BITACORA_FECHA = @FIDE_BITACORA_FECHA,
        FIDE_ESTADO_ID_FK = @FIDE_ESTADO_ID_FK
    WHERE FIDE_BITACORA_ID_PK = @FIDE_BITACORA_ID_PK
      AND FIDE_USUARIOS_ID_FK = @FIDE_USUARIOS_ID_FK;

END;
GO

-------- ELIMINAR EVENTO BITÁCORA --------
CREATE PROCEDURE FIDE_BITACORA_ELIMINAR_LOGICO_SP
    @FIDE_BITACORA_ID_PK INT,
    @FIDE_USUARIOS_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM FIDE_BITACORA_TB 
        WHERE FIDE_BITACORA_ID_PK = @FIDE_BITACORA_ID_PK
          AND FIDE_USUARIOS_ID_FK = @FIDE_USUARIOS_ID_FK
    )
    BEGIN
        RAISERROR('EL EVENTO DE BITÁCORA NO EXISTE EN LA TABLA FIDE_BITACORA_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_BITACORA_TB
    SET FIDE_ESTADO_ID_FK = 2
    WHERE FIDE_BITACORA_ID_PK = @FIDE_BITACORA_ID_PK
      AND FIDE_USUARIOS_ID_FK = @FIDE_USUARIOS_ID_FK;

END;
GO

-----------------DIRECCION_EMPRESA---------------------

SELECT * FROM FIDE_DIRECCION_EMPRESA_TB;
GO 

-------- INSERTAR DIRECCIÓN EMPRESA --------
CREATE PROCEDURE FIDE_DIRECCION_EMPRESA_INSERTAR_SP
    @FIDE_EMPRESA_CEDULA_FK INT,
    @FIDE_PAIS_ID_FK INT,
    @FIDE_PROVINCIA_ID_FK INT,
    @FIDE_CANTON_ID_FK INT,
    @FIDE_DISTRITO_ID_FK INT,
    @FIDE_DIRECCION_OTRAS_SENAS VARCHAR(100),
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF EXISTS (
        SELECT 1 FROM FIDE_DIRECCION_EMPRESA_TB
        WHERE FIDE_EMPRESA_CEDULA_FK = @FIDE_EMPRESA_CEDULA_FK
          AND FIDE_PAIS_ID_FK = @FIDE_PAIS_ID_FK
          AND FIDE_PROVINCIA_ID_FK = @FIDE_PROVINCIA_ID_FK
          AND FIDE_CANTON_ID_FK = @FIDE_CANTON_ID_FK
          AND FIDE_DISTRITO_ID_FK = @FIDE_DISTRITO_ID_FK
    )
    BEGIN
        RAISERROR('LA DIRECCIÓN YA EXISTE EN LA TABLA FIDE_DIRECCION_EMPRESA_TB.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_EMPRESA_TB WHERE FIDE_EMPRESA_CEDULA_PK = @FIDE_EMPRESA_CEDULA_FK)
    BEGIN
        RAISERROR('LA CÉDULA DE EMPRESA NO EXISTE.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_PAIS_TB WHERE FIDE_PAIS_ID_PK = @FIDE_PAIS_ID_FK)
    BEGIN
        RAISERROR('EL PAÍS NO EXISTE.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_PROVINCIA_TB WHERE FIDE_PROVINCIA_ID_PK = @FIDE_PROVINCIA_ID_FK)
    BEGIN
        RAISERROR('LA PROVINCIA NO EXISTE.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_CANTON_TB WHERE FIDE_CANTON_ID_PK = @FIDE_CANTON_ID_FK)
    BEGIN
        RAISERROR('EL CANTÓN NO EXISTE.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_DISTRITO_TB WHERE FIDE_DISTRITO_ID_PK = @FIDE_DISTRITO_ID_FK)
    BEGIN
        RAISERROR('EL DISTRITO NO EXISTE.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM FIDE_ESTADO_TB WHERE FIDE_ESTADO_ID_PK = @FIDE_ESTADO_ID_FK)
    BEGIN
        RAISERROR('EL ESTADO NO EXISTE.', 16, 1);
        RETURN;
    END;

    INSERT INTO FIDE_DIRECCION_EMPRESA_TB (
        FIDE_EMPRESA_CEDULA_FK,
        FIDE_PAIS_ID_FK,
        FIDE_PROVINCIA_ID_FK,
        FIDE_CANTON_ID_FK,
        FIDE_DISTRITO_ID_FK,
        FIDE_DIRECCION_OTRAS_SENAS,
        FIDE_ESTADO_ID_FK
    )
    VALUES (
        @FIDE_EMPRESA_CEDULA_FK,
        @FIDE_PAIS_ID_FK,
        @FIDE_PROVINCIA_ID_FK,
        @FIDE_CANTON_ID_FK,
        @FIDE_DISTRITO_ID_FK,
        @FIDE_DIRECCION_OTRAS_SENAS,
        @FIDE_ESTADO_ID_FK
    );

END;
GO

-------- ACTUALIZAR DIRECCIÓN EMPRESA --------
CREATE PROCEDURE FIDE_DIRECCION_EMPRESA_ACTUALIZAR_SP
    @FIDE_EMPRESA_CEDULA_FK INT,
    @FIDE_PAIS_ID_FK INT,
    @FIDE_PROVINCIA_ID_FK INT,
    @FIDE_CANTON_ID_FK INT,
    @FIDE_DISTRITO_ID_FK INT,
    @FIDE_DIRECCION_OTRAS_SENAS VARCHAR(100),
    @FIDE_ESTADO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM FIDE_DIRECCION_EMPRESA_TB
        WHERE FIDE_EMPRESA_CEDULA_FK = @FIDE_EMPRESA_CEDULA_FK
          AND FIDE_PAIS_ID_FK = @FIDE_PAIS_ID_FK
          AND FIDE_PROVINCIA_ID_FK = @FIDE_PROVINCIA_ID_FK
          AND FIDE_CANTON_ID_FK = @FIDE_CANTON_ID_FK
          AND FIDE_DISTRITO_ID_FK = @FIDE_DISTRITO_ID_FK
    )
    BEGIN
        RAISERROR('LA DIRECCIÓN NO EXISTE EN LA TABLA FIDE_DIRECCION_EMPRESA_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_DIRECCION_EMPRESA_TB
    SET FIDE_DIRECCION_OTRAS_SENAS = @FIDE_DIRECCION_OTRAS_SENAS,
        FIDE_ESTADO_ID_FK = @FIDE_ESTADO_ID_FK
    WHERE FIDE_EMPRESA_CEDULA_FK = @FIDE_EMPRESA_CEDULA_FK
      AND FIDE_PAIS_ID_FK = @FIDE_PAIS_ID_FK
      AND FIDE_PROVINCIA_ID_FK = @FIDE_PROVINCIA_ID_FK
      AND FIDE_CANTON_ID_FK = @FIDE_CANTON_ID_FK
      AND FIDE_DISTRITO_ID_FK = @FIDE_DISTRITO_ID_FK;

END;
GO

-------- ELIMINAR DIRECCIÓN EMPRESA --------
CREATE PROCEDURE FIDE_DIRECCION_EMPRESA_ELIMINAR_LOGICO_SP
    @FIDE_EMPRESA_CEDULA_FK INT,
    @FIDE_PAIS_ID_FK INT,
    @FIDE_PROVINCIA_ID_FK INT,
    @FIDE_CANTON_ID_FK INT,
    @FIDE_DISTRITO_ID_FK INT
AS
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM FIDE_DIRECCION_EMPRESA_TB
        WHERE FIDE_EMPRESA_CEDULA_FK = @FIDE_EMPRESA_CEDULA_FK
          AND FIDE_PAIS_ID_FK = @FIDE_PAIS_ID_FK
          AND FIDE_PROVINCIA_ID_FK = @FIDE_PROVINCIA_ID_FK
          AND FIDE_CANTON_ID_FK = @FIDE_CANTON_ID_FK
          AND FIDE_DISTRITO_ID_FK = @FIDE_DISTRITO_ID_FK
    )
    BEGIN
        RAISERROR('LA DIRECCIÓN NO EXISTE EN LA TABLA FIDE_DIRECCION_EMPRESA_TB.', 16, 1);
        RETURN;
    END;

    UPDATE FIDE_DIRECCION_EMPRESA_TB
    SET FIDE_ESTADO_ID_FK = 2
    WHERE FIDE_EMPRESA_CEDULA_FK = @FIDE_EMPRESA_CEDULA_FK
      AND FIDE_PAIS_ID_FK = @FIDE_PAIS_ID_FK
      AND FIDE_PROVINCIA_ID_FK = @FIDE_PROVINCIA_ID_FK
      AND FIDE_CANTON_ID_FK = @FIDE_CANTON_ID_FK
      AND FIDE_DISTRITO_ID_FK = @FIDE_DISTRITO_ID_FK;

END;
GO
