USE GESTION_VENTAS;
GO

-----------------ESTADO---------------------

SELECT * FROM ESTADO;

-------- INSERTAR ESTADO --------
CREATE PROCEDURE ESTADO_INSERTAR_SP
		@ID_ESTADO INT,
		@TIPO_ESTADO VARCHAR(40)
AS
BEGIN
	IF EXISTS (SELECT 1 FROM ESTADO WHERE ID_ESTADO = @ID_ESTADO)
	BEGIN
		RAISERROR('EL ID_ESTADO YA EXISTE EN LA TABLA ESTADO', 16,1);
		RETURN;
	END;

	INSERT INTO ESTADO(ID_ESTADO, TIPO_ESTADO)
	VALUES(@ID_ESTADO, @TIPO_ESTADO);

END;
GO

-------- ACTUALIZAR ESTADO --------
CREATE PROCEDURE ESTADO_ACTUALIZAR_SP
		@ID_ESTADO INT,
		@TIPO_ESTADO VARCHAR(40)
AS
BEGIN
	IF NOT EXISTS (SELECT 1 FROM ESTADO WHERE ID_ESTADO = @ID_ESTADO)
	BEGIN
		RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA', 16,1);
		RETURN;
	END;

	UPDATE ESTADO
	SET TIPO_ESTADO = @TIPO_ESTADO
	WHERE ID_ESTADO = @ID_ESTADO

END;
GO

-----------------PAIS---------------------

SELECT * FROM PAIS;

-------- INSERTAR PAIS --------
CREATE PROCEDURE PAIS_INSERTAR_SP
    @NOMBRE_PAIS VARCHAR(100),
    @ID_ESTADO INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM PAIS WHERE NOMBRE_PAIS = @NOMBRE_PAIS)
    BEGIN
        RAISERROR('EL NOMBRE DEL PAIS YA EXISTE EN LA TABLA PAIS.', 16, 1);
        RETURN;
    END

    IF NOT EXISTS (SELECT 1 FROM ESTADO WHERE ID_ESTADO = @ID_ESTADO)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA ESTADO.', 16, 1);
        RETURN;
    END;

    INSERT INTO PAIS (NOMBRE_PAIS, ID_ESTADO)
    VALUES (@NOMBRE_PAIS, @ID_ESTADO);

END;
GO

-------- ACTUALIZAR PAIS --------
CREATE PROCEDURE PAIS_ACTUALIZAR_SP
    @ID_PAIS INT,
    @NOMBRE_PAIS VARCHAR(100),
    @ID_ESTADO INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM PAIS WHERE ID_PAIS = @ID_PAIS)
    BEGIN
        RAISERROR('EL ID_PAIS NO EXISTE EN LA TABLA PAIS.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM ESTADO WHERE ID_ESTADO = @ID_ESTADO)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA ESTADO.', 16, 1);
        RETURN;
    END;

    UPDATE PAIS
    SET NOMBRE_PAIS = @NOMBRE_PAIS,
        ID_ESTADO = @ID_ESTADO
    WHERE ID_PAIS = @ID_PAIS;

END;
GO

-------- ELIMINAR PAIS --------
CREATE PROCEDURE PAIS_ELIMINAR_LOGICO_SP
    @ID_PAIS INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM PAIS WHERE ID_PAIS = @ID_PAIS)
    BEGIN
        RAISERROR('EL ID_PAIS NO EXISTE EN LA TABLA PAIS.', 16, 1);
        RETURN;
    END;

    UPDATE PAIS
    SET ID_ESTADO = 2
    WHERE ID_PAIS = @ID_PAIS;

END;
GO

-----------------PROVINCIA---------------------

SELECT * FROM PROVINCIA;

-------- INSERTAR PROVINCIA --------
CREATE PROCEDURE PROVINCIA_INSERTAR_SP
    @NOMBRE_PROVINCIA VARCHAR(100),
    @ID_ESTADO INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM PROVINCIA WHERE NOMBRE_PROVINCIA = @NOMBRE_PROVINCIA)
    BEGIN
        RAISERROR('EL NOMBRE DE LA PROVINCIA YA EXISTE EN LA TABLA PROVINCIA.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM ESTADO WHERE ID_ESTADO = @ID_ESTADO)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA ESTADO.', 16, 1);
        RETURN;
    END;

    INSERT INTO PROVINCIA (NOMBRE_PROVINCIA, ID_ESTADO)
    VALUES (@NOMBRE_PROVINCIA, @ID_ESTADO);

END;
GO

-------- ACTUALIZAR PROVINCIA --------
CREATE PROCEDURE PROVINCIA_ACTUALIZAR_SP
    @ID_PROVINCIA INT,
    @NOMBRE_PROVINCIA VARCHAR(100),
    @ID_ESTADO INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM PROVINCIA WHERE ID_PROVINCIA = @ID_PROVINCIA)
    BEGIN
        RAISERROR('EL ID_PROVINCIA NO EXISTE EN LA TABLA PROVINCIA.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM ESTADO WHERE ID_ESTADO = @ID_ESTADO)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA ESTADO.', 16, 1);
        RETURN;
    END;

    UPDATE PROVINCIA
    SET NOMBRE_PROVINCIA = @NOMBRE_PROVINCIA,
        ID_ESTADO = @ID_ESTADO
    WHERE ID_PROVINCIA = @ID_PROVINCIA;

END;
GO

-------- ELIMINAR PROVINCIA --------
CREATE PROCEDURE PROVINCIA_ELIMINAR_LOGICO_SP
    @ID_PROVINCIA INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM PROVINCIA WHERE ID_PROVINCIA = @ID_PROVINCIA)
    BEGIN
        RAISERROR('EL ID_PROVINCIA NO EXISTE EN LA TABLA PROVINCIA.', 16, 1);
        RETURN;
    END;

    UPDATE PROVINCIA
    SET ID_ESTADO = 2
    WHERE ID_PROVINCIA = @ID_PROVINCIA;

END;
GO

-----------------CANTON---------------------

SELECT * FROM CANTON;

-------- INSERTAR CANTON --------
CREATE PROCEDURE CANTON_INSERTAR_SP
    @NOMBRE_CANTON VARCHAR(100),
    @ID_ESTADO INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM CANTON WHERE NOMBRE_CANTON = @NOMBRE_CANTON)
    BEGIN
        RAISERROR('EL NOMBRE DEL CANTON YA EXISTE EN LA TABLA CANTON.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM ESTADO WHERE ID_ESTADO = @ID_ESTADO)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA ESTADO.', 16, 1);
        RETURN;
    END;

    INSERT INTO CANTON (NOMBRE_CANTON, ID_ESTADO)
    VALUES (@NOMBRE_CANTON, @ID_ESTADO);

END;
GO

-------- ACTUALIZAR CANTON --------
CREATE PROCEDURE CANTON_ACTUALIZAR_SP
    @ID_CANTON INT,
    @NOMBRE_CANTON VARCHAR(100),
    @ID_ESTADO INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM CANTON WHERE ID_CANTON = @ID_CANTON)
    BEGIN
        RAISERROR('EL ID_CANTON NO EXISTE EN LA TABLA CANTON.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM ESTADO WHERE ID_ESTADO = @ID_ESTADO)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA ESTADO.', 16, 1);
        RETURN;
    END;

    UPDATE CANTON
    SET NOMBRE_CANTON = @NOMBRE_CANTON,
        ID_ESTADO = @ID_ESTADO
    WHERE ID_CANTON = @ID_CANTON;

END;
GO

-------- ELIMINAR CANTON --------
CREATE PROCEDURE CANTON_ELIMINAR_LOGICO_SP
    @ID_CANTON INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM CANTON WHERE ID_CANTON = @ID_CANTON)
    BEGIN
        RAISERROR('EL ID_CANTON NO EXISTE EN LA TABLA CANTON.', 16, 1);
        RETURN;
    END;

    UPDATE CANTON
    SET ID_ESTADO = 2
    WHERE ID_CANTON = @ID_CANTON;

END;
GO

-----------------DISTRITO---------------------

SELECT * FROM DISTRITO;

-------- INSERTAR DISTRITO --------
CREATE PROCEDURE DISTRITO_INSERTAR_SP
    @NOMBRE_DISTRITO VARCHAR(100),
    @ID_ESTADO INT
AS
BEGIN
	IF EXISTS (SELECT 1 FROM DISTRITO WHERE NOMBRE_DISTRITO = @NOMBRE_DISTRITO)
    BEGIN
        RAISERROR('EL NOMBRE DEL DISTRITO YA EXISTE EN LA TABLA DISTRITO.', 16, 1);
        RETURN;
    END;

	IF NOT EXISTS (SELECT 1 FROM ESTADO WHERE ID_ESTADO = @ID_ESTADO)
    BEGIN
        RAISERROR('El ID_ESTADO NO EXISTE EN LA TABLA ESTADO.', 16, 1);
        RETURN;
    END;

    INSERT INTO DISTRITO (NOMBRE_DISTRITO, ID_ESTADO)
    VALUES (@NOMBRE_DISTRITO, @ID_ESTADO);

END;
GO

-------- ACTUALIZAR DISTRITO --------
CREATE PROCEDURE DISTRITO_ACTUALIZAR_SP
    @ID_DISTRITO INT,
    @NOMBRE_DISTRITO VARCHAR(100),
    @ID_ESTADO INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM DISTRITO WHERE ID_DISTRITO = @ID_DISTRITO)
    BEGIN
        RAISERROR('El ID_DISTRITO YA EXISTE EN LA TABLA ESTADO DISTRITO.', 16, 1);
        RETURN;
    END;

	IF NOT EXISTS (SELECT 1 FROM ESTADO WHERE ID_ESTADO = @ID_ESTADO)
    BEGIN
        RAISERROR('El ID_ESTADO NO EXISTE EN LA TABLA ESTADO.', 16, 1);
        RETURN;
    END;

    UPDATE DISTRITO
    SET NOMBRE_DISTRITO = @NOMBRE_DISTRITO,
        ID_ESTADO = @ID_ESTADO
    WHERE ID_DISTRITO = @ID_DISTRITO;

END;
GO

-------- ELIMINAR DISTRITO --------
CREATE PROCEDURE DISTRITO_ELIMINAR_LOGICO_SP
    @ID_DISTRITO INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM DISTRITO WHERE ID_DISTRITO = @ID_DISTRITO)
    BEGIN
        RAISERROR('El ID_DISTRITO NO EXISTE EN LA TABLA DISTRITO.', 16, 1);
        RETURN;
    END;

    UPDATE DISTRITO
    SET ID_ESTADO = 2
    WHERE ID_DISTRITO = @ID_DISTRITO;

END;
GO

-----------------ROLES---------------------

SELECT * FROM ROLES;

-------- INSERTAR ROL --------
CREATE PROCEDURE ROL_INSERTAR_SP
    @ROL_NOMBRE VARCHAR(100),
    @ID_ESTADO INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM ROLES WHERE ROL_NOMBRE = @ROL_NOMBRE)
    BEGIN
        RAISERROR('EL NOMBRE DEL ROL YA EXISTE EN LA TABLA ROLES.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM ESTADO WHERE ID_ESTADO = @ID_ESTADO)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA ESTADO.', 16, 1);
        RETURN;
    END;

    INSERT INTO ROLES (ROL_NOMBRE, ID_ESTADO)
    VALUES (@ROL_NOMBRE, @ID_ESTADO);

END;
GO

-------- ACTUALIZAR ROL --------
CREATE PROCEDURE ROL_ACTUALIZAR_SP
    @ID_ROL INT,
    @ROL_NOMBRE VARCHAR(100),
    @ID_ESTADO INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM ROLES WHERE ID_ROL = @ID_ROL)
    BEGIN
        RAISERROR('EL ID_ROL NO EXISTE EN LA TABLA ROLES.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM ESTADO WHERE ID_ESTADO = @ID_ESTADO)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA ESTADO.', 16, 1);
        RETURN;
    END;

    UPDATE ROLES
    SET ROL_NOMBRE = @ROL_NOMBRE,
        ID_ESTADO = @ID_ESTADO
    WHERE ID_ROL = @ID_ROL;

END;
GO

-------- ELIMINAR ROL --------
CREATE PROCEDURE ROL_ELIMINAR_LOGICO_SP
    @ID_ROL INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM ROLES WHERE ID_ROL = @ID_ROL)
    BEGIN
        RAISERROR('EL ID_ROL NO EXISTE EN LA TABLA ROLES.', 16, 1);
        RETURN;
    END;

    UPDATE ROLES
    SET ID_ESTADO = 2
    WHERE ID_ROL = @ID_ROL;

END;
GO

-----------------USUARIOS---------------------

SELECT * FROM USUARIOS;

-------- INSERTAR USUARIO --------
CREATE PROCEDURE USUARIO_INSERTAR_SP
    @NOMBRE_USUARIO VARCHAR(100),
    @APELLIDO_UNO VARCHAR(100),
    @APELLIDO_DOS VARCHAR(100),
    @USUARIO_RED VARCHAR(100),
    @PASS VARCHAR(100),
    @ID_ROL INT,
    @ID_ESTADO INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM USUARIOS WHERE NOMBRE_USUARIO = @NOMBRE_USUARIO)
    BEGIN
        RAISERROR('EL NOMBRE DEL USUARIO YA EXISTE EN LA TABLA USUARIOS.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM ESTADO WHERE ID_ESTADO = @ID_ESTADO)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA ESTADO.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM ROLES WHERE ID_ROL = @ID_ROL)
    BEGIN
        RAISERROR('EL ID_ROL NO EXISTE EN LA TABLA ROLES.', 16, 1);
        RETURN;
    END;

    INSERT INTO USUARIOS (
        NOMBRE_USUARIO, APELLIDO_UNO, APELLIDO_DOS,
        USUARIO_RED, PASS, ID_ROL, ID_ESTADO
    )
    VALUES (
        @NOMBRE_USUARIO, @APELLIDO_UNO, @APELLIDO_DOS,
        @USUARIO_RED, @PASS, @ID_ROL, @ID_ESTADO
    );

END;
GO

-------- ACTUALIZAR USUARIO --------
CREATE PROCEDURE USUARIO_ACTUALIZAR_SP
    @ID_USUARIO INT,
    @NOMBRE_USUARIO VARCHAR(100),
    @APELLIDO_UNO VARCHAR(100),
    @APELLIDO_DOS VARCHAR(100),
    @USUARIO_RED VARCHAR(100),
    @PASS VARCHAR(100),
    @ID_ROL INT,
    @ID_ESTADO INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM USUARIOS WHERE ID_USUARIO = @ID_USUARIO)
    BEGIN
        RAISERROR('EL ID_USUARIO NO EXISTE EN LA TABLA USUARIOS.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM ROLES WHERE ID_ROL = @ID_ROL)
    BEGIN
        RAISERROR('EL ID_ROL NO EXISTE EN LA TABLA ROLES.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM ESTADO WHERE ID_ESTADO = @ID_ESTADO)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA ESTADO.', 16, 1);
        RETURN;
    END;

    UPDATE USUARIOS
    SET NOMBRE_USUARIO = @NOMBRE_USUARIO,
        APELLIDO_UNO = @APELLIDO_UNO,
        APELLIDO_DOS = @APELLIDO_DOS,
        USUARIO_RED = @USUARIO_RED,
        PASS = @PASS,
        ID_ROL = @ID_ROL,
        ID_ESTADO = @ID_ESTADO
    WHERE ID_USUARIO = @ID_USUARIO;

END;
GO

-------- ELIMINAR USUARIO --------
CREATE PROCEDURE USUARIO_ELIMINAR_LOGICO_SP
    @ID_USUARIO INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM USUARIOS WHERE ID_USUARIO = @ID_USUARIO)
    BEGIN
        RAISERROR('EL ID_USUARIO NO EXISTE EN LA TABLA USUARIOS.', 16, 1);
        RETURN;
    END;

    UPDATE USUARIOS
    SET ID_ESTADO = 2
    WHERE ID_USUARIO = @ID_USUARIO;

END;
GO

-----------------EMPRESA---------------------

SELECT * FROM EMPRESA;

-------- INSERTAR EMPRESA --------
CREATE PROCEDURE EMPRESA_INSERTAR_SP
    @CEDULA_JURIDICA INT,
    @NOMBRE_EMPRESA VARCHAR(100),
    @TELEFONO_EMPRESA VARCHAR(100),
    @CORREO_EMPRESA VARCHAR(100),
    @ID_ESTADO INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM EMPRESA WHERE CEDULA_JURIDICA = @CEDULA_JURIDICA)
    BEGIN
        RAISERROR('YA EXISTE ESA CÉDULA JURÍDICA.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM ESTADO WHERE ID_ESTADO = @ID_ESTADO)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA ESTADO.', 16, 1);
        RETURN;
    END;

    INSERT INTO EMPRESA (
        CEDULA_JURIDICA, NOMBRE_EMPRESA, TELEFONO_EMPRESA,
        CORREO_EMPRESA, ID_ESTADO
    )
    VALUES (
        @CEDULA_JURIDICA, @NOMBRE_EMPRESA, @TELEFONO_EMPRESA,
        @CORREO_EMPRESA, @ID_ESTADO
    );

END;
GO

-------- ACTUALIZAR EMPRESA --------
CREATE PROCEDURE EMPRESA_ACTUALIZAR_SP
    @CEDULA_JURIDICA INT,
    @NOMBRE_EMPRESA VARCHAR(100),
    @TELEFONO_EMPRESA VARCHAR(100),
    @CORREO_EMPRESA VARCHAR(100),
    @ID_ESTADO INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM EMPRESA WHERE CEDULA_JURIDICA = @CEDULA_JURIDICA)
    BEGIN
        RAISERROR('LA CÉDULA JURÍDICA NO EXISTE EN LA TABLA EMPRESA.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM ESTADO WHERE ID_ESTADO = @ID_ESTADO)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA ESTADO.', 16, 1);
        RETURN;
    END;

    UPDATE EMPRESA
    SET NOMBRE_EMPRESA = @NOMBRE_EMPRESA,
        TELEFONO_EMPRESA = @TELEFONO_EMPRESA,
        CORREO_EMPRESA = @CORREO_EMPRESA,
        ID_ESTADO = @ID_ESTADO
    WHERE CEDULA_JURIDICA = @CEDULA_JURIDICA;

END;
GO

-------- ELIMINAR EMPRESA --------
CREATE PROCEDURE EMPRESA_ELIMINAR_LOGICO_SP
    @CEDULA_JURIDICA INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM EMPRESA WHERE CEDULA_JURIDICA = @CEDULA_JURIDICA)
    BEGIN
        RAISERROR('LA CÉDULA JURÍDICA NO EXISTE EN LA TABLA EMPRESA.', 16, 1);
        RETURN;
    END;

    UPDATE EMPRESA
    SET ID_ESTADO = 2
    WHERE CEDULA_JURIDICA = @CEDULA_JURIDICA;

END;
GO

-----------------CATEGORIAS---------------------

SELECT * FROM CATEGORIAS;

-------- INSERTAR CATEGORIA --------
CREATE PROCEDURE CATEGORIA_INSERTAR_SP
    @NOMBRE_CATEGORIA VARCHAR(100),
    @DESCRIPCION_CATEGORIA VARCHAR(100),
    @ID_ESTADO INT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM CATEGORIAS WHERE NOMBRE_CATEGORIA = @NOMBRE_CATEGORIA)
    BEGIN
        RAISERROR('YA EXISTE UNA CATEGORÍA CON ESE NOMBRE.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM ESTADO WHERE ID_ESTADO = @ID_ESTADO)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA ESTADO.', 16, 1);
        RETURN;
    END;

    INSERT INTO CATEGORIAS (
        NOMBRE_CATEGORIA, DESCRIPCION_CATEGORIA, ID_ESTADO
    )
    VALUES (
        @NOMBRE_CATEGORIA, @DESCRIPCION_CATEGORIA, @ID_ESTADO
    );

END;
GO

-------- ACTUALIZAR CATEGORIA --------
CREATE PROCEDURE CATEGORIA_ACTUALIZAR_SP
    @ID_CATEGORIA INT,
    @NOMBRE_CATEGORIA VARCHAR(100),
    @DESCRIPCION_CATEGORIA VARCHAR(100),
    @ID_ESTADO INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM CATEGORIAS WHERE ID_CATEGORIA = @ID_CATEGORIA)
    BEGIN
        RAISERROR('EL ID_CATEGORIA NO EXISTE EN LA TABLA CATEGORIAS.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM ESTADO WHERE ID_ESTADO = @ID_ESTADO)
    BEGIN
        RAISERROR('EL ID_ESTADO NO EXISTE EN LA TABLA ESTADO.', 16, 1);
        RETURN;
    END;

    UPDATE CATEGORIAS
    SET NOMBRE_CATEGORIA = @NOMBRE_CATEGORIA,
        DESCRIPCION_CATEGORIA = @DESCRIPCION_CATEGORIA,
        ID_ESTADO = @ID_ESTADO
    WHERE ID_CATEGORIA = @ID_CATEGORIA;

END;
GO

-------- ELIMINAR CATEGORIA --------
CREATE PROCEDURE CATEGORIA_ELIMINAR_LOGICO_SP
    @ID_CATEGORIA INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM CATEGORIAS WHERE ID_CATEGORIA = @ID_CATEGORIA)
    BEGIN
        RAISERROR('EL ID_CATEGORIA NO EXISTE EN LA TABLA CATEGORIAS.', 16, 1);
        RETURN;
    END;

    UPDATE CATEGORIAS
    SET ID_ESTADO = 2
    WHERE ID_CATEGORIA = @ID_CATEGORIA;

END;
GO