USE GESTION_VENTAS;
GO

---TRIGGERS---
--TRIGGER DE ESTADO--
--INSERT--
CREATE TRIGGER FIDE_ESTADO_TB_INSERT_TR
ON FIDE_ESTADO_TB
AFTER INSERT
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(1, 'FIDE_ESTADO_TB', GETDATE(), 1);
END;
GO

--UPDATE--
CREATE TRIGGER FIDE_ESTADO_TB_UPDATE_TR
ON FIDE_ESTADO_TB
AFTER UPDATE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(2, 'FIDE_ESTADO_TB', GETDATE(), 1);
END;
GO

--DELETE--
CREATE TRIGGER FIDE_ESTADO_TB_DELETE_TR
ON FIDE_ESTADO_TB
AFTER DELETE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(3, 'FIDE_ESTADO_TB', GETDATE(), 1);
END;
GO

--TRIGGER DE PAIS--

--INSERTAR--
CREATE TRIGGER FIDE_PAIS_TB_INSERT_TR
ON FIDE_PAIS_TB
AFTER INSERT
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(1, 'FIDE_PAIS_TB', GETDATE(), 1);
END;
GO

--UPDATE--
CREATE TRIGGER FIDE_PAIS_TB_UPDATE_TR
ON FIDE_PAIS_TB
AFTER UPDATE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(2, 'FIDE_PAIS_TB', GETDATE(), 1);
END;
GO

--DELETE--
CREATE TRIGGER FIDE_PAIS_TB_DELETE_TR
ON FIDE_PAIS_TB
AFTER DELETE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(3, 'FIDE_PAIS_TB', GETDATE(), 1);
END;
GO

--BITACORA--
--INSERTAR--
CREATE TRIGGER FIDE_BITACORA_TB_INSERT_TR
ON FIDE_BITACORA_TB
AFTER INSERT
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(1, 'FIDE_BITACORA_TB', GETDATE(), 1);
END;
GO

--UPDATE--
CREATE TRIGGER FIDE_BITACORA_TB_UPDATE_TR
ON FIDE_BITACORA_TB
AFTER UPDATE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(2, 'FIDE_BITACORA_TB', GETDATE(), 1);
END;
GO

--DELETE--
CREATE TRIGGER FIDE_BITACORA_TB_DELETE_TR
ON FIDE_BITACORA_TB
AFTER DELETE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(3, 'FIDE_BITACORA_TB', GETDATE(), 1);
END;
GO
--CANTON-- 
--INSERTAR--
CREATE TRIGGER FIDE_CANTON_TB_INSERT_TR
ON FIDE_CANTON_TB
AFTER INSERT
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(1, 'FIDE_CANTON_TB', GETDATE(), 1);
END;
GO

--UPDATE--
CREATE TRIGGER FIDE_CANTON_TB_UPDATE_TR
ON FIDE_CANTON_TB
AFTER UPDATE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(2, 'FIDE_CANTON_TB', GETDATE(), 1);
END;
GO

--DELETE--
CREATE TRIGGER FIDE_CANTON_TB_DELETE_TR
ON FIDE_CANTON_TB
AFTER DELETE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(3, 'FIDE_CANTON_TB', GETDATE(), 1);
END;
GO
--CATEGORIAS--
--INSERTAR--
CREATE TRIGGER FIDE_CATEGORIAS_TB_INSERT_TR
ON FIDE_CATEGORIAS_TB
AFTER INSERT
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(1, 'FIDE_CATEGORIAS_TB', GETDATE(), 1);
END;
GO

--UPDATE--
CREATE TRIGGER FIDE_CATEGORIAS_TB_UPDATE_TR
ON FIDE_CATEGORIAS_TB
AFTER UPDATE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(2, 'FIDE_CATEGORIAS_TB', GETDATE(), 1);
END;
GO

--DELETE--
CREATE TRIGGER FIDE_CATEGORIAS_TB_DELETE_TR
ON FIDE_CATEGORIAS_TB
AFTER DELETE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(3, 'FIDE_CATEGORIAS_TB', GETDATE(), 1);
END;
GO
--DETALLE_VENTA--
--INSERTAR--
CREATE TRIGGER FIDE_DETALLE_VENTA_TB_INSERT_TR
ON FIDE_DETALLE_VENTA_TB
AFTER INSERT
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(1, 'FIDE_DETALLE_VENTA_TB', GETDATE(), 1);
END;
GO

--UPDATE--
CREATE TRIGGER FIDE_DETALLE_VENTA_TB_UPDATE_TR
ON FIDE_DETALLE_VENTA_TB
AFTER UPDATE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(2, 'FIDE_DETALLE_VENTA_TB', GETDATE(), 1);
END;
GO

--DELETE--
CREATE TRIGGER FIDE_DETALLE_VENTA_TB_DELETE_TR
ON FIDE_DETALLE_VENTA_TB
AFTER DELETE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(3, 'FIDE_DETALLE_VENTA_TB', GETDATE(), 1);
END;
GO
CREATE TRIGGER FIDE_DIRECCION_EMPRESA_TB_INSERT_TR
ON FIDE_DIRECCION_EMPRESA_TB
AFTER INSERT
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(1, 'FIDE_DIRECCION_EMPRESA_TB', GETDATE(), 1);
END;
GO

CREATE TRIGGER FIDE_DIRECCION_EMPRESA_TB_UPDATE_TR
ON FIDE_DIRECCION_EMPRESA_TB
AFTER UPDATE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(2, 'FIDE_DIRECCION_EMPRESA_TB', GETDATE(), 1);
END;
GO

CREATE TRIGGER FIDE_DIRECCION_EMPRESA_TB_DELETE_TR
ON FIDE_DIRECCION_EMPRESA_TB
AFTER DELETE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(3, 'FIDE_DIRECCION_EMPRESA_TB', GETDATE(), 1);
END;
GO
--DISTRITO--
--INSERTAR--
CREATE TRIGGER FIDE_DISTRITO_TB_INSERT_TR
ON FIDE_DISTRITO_TB
AFTER INSERT
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(1, 'FIDE_DISTRITO_TB', GETDATE(), 1);
END;
GO

--UPDATE--
CREATE TRIGGER FIDE_DISTRITO_TB_UPDATE_TR
ON FIDE_DISTRITO_TB
AFTER UPDATE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(2, 'FIDE_DISTRITO_TB', GETDATE(), 1);
END;
GO

--DELETE--
CREATE TRIGGER FIDE_DISTRITO_TB_DELETE_TR
ON FIDE_DISTRITO_TB
AFTER DELETE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(3, 'FIDE_DISTRITO_TB', GETDATE(), 1);
END;
GO
--EMPRESA--
--INSERTAR--
CREATE TRIGGER FIDE_EMPRESA_TB_INSERT_TR
ON FIDE_EMPRESA_TB
AFTER INSERT
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(1, 'FIDE_EMPRESA_TB', GETDATE(), 1);
END;
GO

--UPDATE--
CREATE TRIGGER FIDE_EMPRESA_TB_UPDATE_TR
ON FIDE_EMPRESA_TB
AFTER UPDATE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(2, 'FIDE_EMPRESA_TB', GETDATE(), 1);
END;
GO

--DELETE--
CREATE TRIGGER FIDE_EMPRESA_TB_DELETE_TR
ON FIDE_EMPRESA_TB
AFTER DELETE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(3, 'FIDE_EMPRESA_TB', GETDATE(), 1);
END;
GO
--MOVIMIENTOS_INVENTARIO--
--INSERTAR--
CREATE TRIGGER FIDE_MOVIMIENTOS_INVENTARIO_TB_INSERT_TR
ON FIDE_MOVIMIENTOS_INVENTARIO_TB
AFTER INSERT
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(1, 'FIDE_MOVIMIENTOS_INVENTARIO_TB', GETDATE(), 1);
END;
GO

--UPDATE--
CREATE TRIGGER FIDE_MOVIMIENTOS_INVENTARIO_TB_UPDATE_TR
ON FIDE_MOVIMIENTOS_INVENTARIO_TB
AFTER UPDATE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(2, 'FIDE_MOVIMIENTOS_INVENTARIO_TB', GETDATE(), 1);
END;
GO

--DELETE--
CREATE TRIGGER FIDE_MOVIMIENTOS_INVENTARIO_TB_DELETE_TR
ON FIDE_MOVIMIENTOS_INVENTARIO_TB
AFTER DELETE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(3, 'FIDE_MOVIMIENTOS_INVENTARIO_TB', GETDATE(), 1);
END;
GO
--PRODUCTOS--
--INSERTAR--
CREATE TRIGGER FIDE_PRODUCTOS_TB_INSERT_TR
ON FIDE_PRODUCTOS_TB
AFTER INSERT
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(1, 'FIDE_PRODUCTOS_TB', GETDATE(), 1);
END;
GO

--UPDATE--
CREATE TRIGGER FIDE_PRODUCTOS_TB_UPDATE_TR
ON FIDE_PRODUCTOS_TB
AFTER UPDATE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(2, 'FIDE_PRODUCTOS_TB', GETDATE(), 1);
END;
GO

--DELETE--
CREATE TRIGGER FIDE_PRODUCTOS_TB_DELETE_TR
ON FIDE_PRODUCTOS_TB
AFTER DELETE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(3, 'FIDE_PRODUCTOS_TB', GETDATE(), 1);
END;
GO
CREATE TRIGGER FIDE_PROVINCIA_TB_INSERT_TR
ON FIDE_PROVINCIA_TB
AFTER INSERT
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(1, 'FIDE_PROVINCIA_TB', GETDATE(), 1);
END;
GO

CREATE TRIGGER FIDE_PROVINCIA_TB_UPDATE_TR
ON FIDE_PROVINCIA_TB
AFTER UPDATE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(2, 'FIDE_PROVINCIA_TB', GETDATE(), 1);
END;
GO

CREATE TRIGGER FIDE_PROVINCIA_TB_DELETE_TR
ON FIDE_PROVINCIA_TB
AFTER DELETE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(3, 'FIDE_PROVINCIA_TB', GETDATE(), 1);
END;
GO
--ROLES--
--INSERTAR--
CREATE TRIGGER FIDE_ROLES_TB_INSERT_TR
ON FIDE_ROLES_TB
AFTER INSERT
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(1, 'FIDE_ROLES_TB', GETDATE(), 1);
END;
GO

--UPDATE--
CREATE TRIGGER FIDE_ROLES_TB_UPDATE_TR
ON FIDE_ROLES_TB
AFTER UPDATE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(2, 'FIDE_ROLES_TB', GETDATE(), 1);
END;
GO

--DELETE--
CREATE TRIGGER FIDE_ROLES_TB_DELETE_TR
ON FIDE_ROLES_TB
AFTER DELETE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(3, 'FIDE_ROLES_TB', GETDATE(), 1);
END;
GO
--TIPOS_MOVIMIENTO--
--INSERTAR--
CREATE TRIGGER FIDE_TIPOS_MOVIMIENTO_TB_INSERT_TR
ON FIDE_TIPOS_MOVIMIENTO_TB
AFTER INSERT
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(1, 'FIDE_TIPOS_MOVIMIENTO_TB', GETDATE(), 1);
END;
GO

--UPDATE--
CREATE TRIGGER FIDE_TIPOS_MOVIMIENTO_TB_UPDATE_TR
ON FIDE_TIPOS_MOVIMIENTO_TB
AFTER UPDATE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(2, 'FIDE_TIPOS_MOVIMIENTO_TB', GETDATE(), 1);
END;
GO

--DELETE--
CREATE TRIGGER FIDE_TIPOS_MOVIMIENTO_TB_DELETE_TR
ON FIDE_TIPOS_MOVIMIENTO_TB
AFTER DELETE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(3, 'FIDE_TIPOS_MOVIMIENTO_TB', GETDATE(), 1);
END;
GO
--USUARIOS--
--INSERTAR--
CREATE TRIGGER FIDE_USUARIOS_TB_INSERT_TR
ON FIDE_USUARIOS_TB
AFTER INSERT
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(1, 'FIDE_USUARIOS_TB', GETDATE(), 1);
END;
GO

--UPDATE--
CREATE TRIGGER FIDE_USUARIOS_TB_UPDATE_TR
ON FIDE_USUARIOS_TB
AFTER UPDATE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(2, 'FIDE_USUARIOS_TB', GETDATE(), 1);
END;
GO

--DELETE--
CREATE TRIGGER FIDE_USUARIOS_TB_DELETE_TR
ON FIDE_USUARIOS_TB
AFTER DELETE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(3, 'FIDE_USUARIOS_TB', GETDATE(), 1);
END;
GO
--VENTAS--
--INSERTAR--
CREATE TRIGGER FIDE_VENTAS_TB_INSERT_TR
ON FIDE_VENTAS_TB
AFTER INSERT
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(1, 'FIDE_VENTAS_TB', GETDATE(), 1);
END;
GO

--UPDATE--
CREATE TRIGGER FIDE_VENTAS_TB_UPDATE_TR
ON FIDE_VENTAS_TB
AFTER UPDATE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(2, 'FIDE_VENTAS_TB', GETDATE(), 1);
END;
GO

--DELETE--
CREATE TRIGGER FIDE_VENTAS_TB_DELETE_TR
ON FIDE_VENTAS_TB
AFTER DELETE
AS
BEGIN
INSERT INTO FIDE_AUDITORIA_TB (FIDE_ACCION_AUDITORIA_ID, FIDE_AUDITORIA_TABLA, FIDE_AUDITORIA_FECHA, FIDE_AUDITORIA_ESTADO)
VALUES(3, 'FIDE_VENTAS_TB', GETDATE(), 1);
END;
GO