---- SCRIPT VIEWS PROYECTO FINAL
---VER LA DIRECCION DE UNA EMPRESA
GO 
CREATE VIEW DIRECCION_EMPRESA_VIEW AS
SELECT
	D.CEDULA_JURIDICA AS 'CEDULA JURIDICA',
	P.NOMBRE_PAIS AS 'NOMBRE DEL PAIS',
	PR.NOMBRE_PROVINCIA AS 'NOMBRE DE PROVINCIA',
	C.NOMBRE_CANTON AS 'NOMBRE DEL CANTON',
	DI.NOMBRE_DISTRITO AS 'NOMBRE DEL DISTRITO',
	D.OTRAS_SENAS AS 'OTRAS SEÑAS'
    
   
FROM DIRECCION_EMPRESA D
INNER JOIN PAIS P ON D.ID_PAIS = P.ID_PAIS
INNER JOIN PROVINCIA PR ON D.ID_PROVINCIA = PR.ID_PROVINCIA
INNER JOIN CANTON C ON D.ID_CANTON = C.ID_CANTON
INNER JOIN DISTRITO DI ON D.ID_DISTRITO = DI.ID_DISTRITO

GO
SELECT * FROM DIRECCION_EMPRESA_VIEW;


---VER SI UN USUARIO ESTA ACTIVO EN LA RED 
GO
CREATE VIEW USUARIO_ACTIVO_RED_VIEW AS
SELECT
    U.ID_USUARIO AS 'ID DEL USUARIO',
    U.USUARIO_RED AS 'NOMBRE EN LA RED',
    U.PASS AS 'NUMERO DE PASS',
    E.TIPO_ESTADO AS 'ESTADO DE ACTIVIDAD'
FROM USUARIOS U
INNER JOIN ESTADO E ON U.ID_ESTADO = E.ID_ESTADO

GO
SELECT * FROM USUARIO_ACTIVO_RED_VIEW;


---VER LA CATEGORIA A LA CUAL PERTENECE UN PRODUCTO 
GO
CREATE VIEW CATEGORIA_PRODUCTO_VIEW AS
SELECT
    P.ID_PRODUCTO AS 'ID DEL PRODUCTO',
    P.NOMBRE_PRODUCTO AS 'NOMBRE DEL PRODUCTO',
    P.DESCRIPCION_PRODUCTO AS 'DESCRIPCION DEL PRODUCTO',
	C.NOMBRE_CATEGORIA AS 'NOMBRE DE LA CATEOGORIA',
	C.DESCRIPCION_CATEGORIA AS 'DESCRIPCION DE LA CATEOGORIA'
FROM PRODUCTOS P
INNER JOIN CATEGORIAS C ON P.ID_CATEGORIA = C.ID_CATEGORIA

GO
SELECT * FROM CATEGORIA_PRODUCTO_VIEW;

---VER LA PERSONA RELACIONADA CON UNA BITACORA 
GO
CREATE VIEW USUARIO_EN_BITACORA_VIEW AS
SELECT
    
    B.ID_USUARIO AS 'ID DEL USUARIO',
	B.ID_BITACORA AS 'ID DE LA BITACORA',
	B.FECHA_BITACORA AS 'FECHA DE LA BITACORA',
	U.NOMBRE_USUARIO AS 'NOMBRE',
    U.APELLIDO_UNO AS 'PRIMER APELLIDO',
    U.APELLIDO_DOS AS 'SEGUNDO APELLIDO',
    U.USUARIO_RED AS 'NOMBRE EN LA RED'
FROM BITACORA B
INNER JOIN USUARIOS U ON B.ID_USUARIO = U.ID_USUARIO

GO
SELECT * FROM USUARIO_EN_BITACORA_VIEW;


---VER SI UNA EMPRESA ESTA ACTIVA 
GO 
CREATE VIEW ESTADO_EMPRESA_VIEW AS
SELECT
	E.CEDULA_JURIDICA AS 'CEDULA JURIDICA',
	E.NOMBRE_EMPRESA AS 'NOMBRE DE LA EMPRESA',
	ES.TIPO_ESTADO AS 'ESTADO DE LA EMPRESA'
   
FROM EMPRESA E
INNER JOIN ESTADO ES ON E.ID_ESTADO = ES.ID_ESTADO

GO
SELECT * FROM ESTADO_EMPRESA_VIEW;

---VER INFORMACION DE VENTA CON EMPRESA 
GO
CREATE VIEW EMPRESA_VENTA_VIEW AS
SELECT
    V.ID_VENTA AS 'ID DE LA VENTA',
    V.FECHA_VENTA AS 'FECHA',
    E.NOMBRE_EMPRESA AS 'EMPRESA'

FROM VENTAS V
INNER JOIN EMPRESA E ON V.CEDULA_JURIDICA = E.CEDULA_JURIDICA
GO

SELECT * FROM EMPRESA_VENTA_VIEW;



---VER EL ROL DE UN USUARIO 7
GO 
CREATE VIEW USUARIO_ROL_VIEW AS
SELECT
	U.ID_USUARIO AS 'ID DEL USUARIO',
	U.NOMBRE_USUARIO AS 'NOMBRE',
    U.APELLIDO_UNO AS 'PRIMER APELLIDO',
    U.APELLIDO_DOS AS 'SEGUNDO APELLIDO',
    R.ROL_NOMBRE AS 'TIPO DEL ROL'
	
   
FROM USUARIOS U
INNER JOIN ROLES R ON U.ID_ROL = R.ID_ROL

GO
SELECT * FROM USUARIO_ROL_VIEW;

---VER DETTALE DE VENTA CON PRODUCTOS 8
GO
CREATE VIEW DETALLE_VENTA_PRODUCTO_VIEW AS
SELECT
    D.ID_DETALLE AS 'ID DEL DETALLE',
    D.ID_VENTA AS 'ID DE LA VENTA',
    D.CANTIDAD_VENDIDA AS 'CANTIDAD',
	P.NOMBRE_PRODUCTO AS 'PRODUCTO VENDIDO',
    E.TIPO_ESTADO AS 'ESTADO DEL DETALLE'
FROM DETALLE_VENTA D
INNER JOIN PRODUCTOS P ON D.ID_PRODUCTO = P.ID_PRODUCTO
INNER JOIN ESTADO E ON D.ID_ESTADO = E.ID_ESTADO
GO

SELECT * FROM DETALLE_VENTA_PRODUCTO_VIEW;

---ER INFOMRACION DE VENTA POR UN USUARIO 9
GO
CREATE VIEW USUARIO_VENTA_VIEW AS
SELECT
    V.ID_VENTA AS 'ID DE LA VENTA',
    V.FECHA_VENTA AS 'FECHA',
    U.NOMBRE_USUARIO AS 'NOMBRE DEL USUARIO',
	U.APELLIDO_UNO AS 'PRIMER APELLIDO',
	U.APELLIDO_DOS  AS 'SEGUNDO APELLIDO'
FROM VENTAS V
INNER JOIN USUARIOS U ON V.ID_USUARIO = U.ID_USUARIO
GO


SELECT * FROM USUARIO_VENTA_VIEW;

---VER EL TIPO DE MOVIMIENTO DE UN MOVIMIENTO 
GO
CREATE VIEW DETALLE_TIPO_MOVIMIENTO_VIEW AS
SELECT
	M.ID_MOVIMIENTO AS 'ID DEL MOVIMIENTO',
	M.ID_PRODUCTO AS 'ID DEL PRODUCTO',
	M.DETALLES_MOVIMIENTO AS 'DETALLES DEL MOVIMIENTO',
	T.NOMBRE_MOVIMIENTO AS 'TIPO DEL MOVIMIENTO'

FROM MOVIMIENTOS_INVENTARIO M
INNER JOIN TIPOS_MOVIMIENTO T ON M.ID_TIPO_MOVIMIENTO = T.ID_TIPO_MOVIMIENTO

GO

SELECT * FROM DETALLE_TIPO_MOVIMIENTO_VIEW;