USE GESTION_VENTAS;
GO
	
---VER LA DIRECCION DE UNA EMPRESA
GO
CREATE VIEW FIDE_DIRECCION_EMPRESA_V AS
SELECT
    D.FIDE_EMPRESA_CEDULA_FK AS 'CEDULA JURIDICA',
    P.FIDE_PAIS_NOMBRE AS 'NOMBRE DEL PAIS',
    PR.FIDE_PROVINCIA_NOMBRE AS 'NOMBRE DE PROVINCIA',
    C.FIDE_CANTON_NOMBRE AS 'NOMBRE DEL CANTON',
    DI.FIDE_DISTRITO_NOMBRE AS 'NOMBRE DEL DISTRITO',
    D.FIDE_DIRECCION_OTRAS_SENAS AS 'OTRAS SEÑAS'
FROM FIDE_DIRECCION_EMPRESA_TB D
INNER JOIN FIDE_PAIS_TB P ON D.FIDE_PAIS_ID_FK = P.FIDE_PAIS_ID_PK
INNER JOIN FIDE_PROVINCIA_TB PR ON D.FIDE_PROVINCIA_ID_FK = PR.FIDE_PROVINCIA_ID_PK
INNER JOIN FIDE_CANTON_TB C ON D.FIDE_CANTON_ID_FK = C.FIDE_CANTON_ID_PK
INNER JOIN FIDE_DISTRITO_TB DI ON D.FIDE_DISTRITO_ID_FK = DI.FIDE_DISTRITO_ID_PK
GO
SELECT * FROM FIDE_DIRECCION_EMPRESA_V;



---VER SI UN USUARIO ESTA ACTIVO EN LA RED 
GO
CREATE VIEW FIDE_USUARIOS_ACTIVOS_V AS
SELECT
    U.FIDE_USUARIOS_ID_PK AS 'ID DEL USUARIO',
    U.FIDE_USUARIOS_RED AS 'NOMBRE EN LA RED',
    U.FIDE_USUARIOS_PASS AS 'NUMERO DE PASS',
    E.FIDE_ESTADO_TIPO AS 'ESTADO DE ACTIVIDAD'
FROM FIDE_USUARIOS_TB U
INNER JOIN FIDE_ESTADO_TB E ON U.FIDE_ESTADO_ID_FK = E.FIDE_ESTADO_ID_PK
GO

SELECT * FROM FIDE_USUARIOS_ACTIVOS_V;



---VER LA CATEGORIA A LA CUAL PERTENECE UN PRODUCTO 
GO
CREATE VIEW FIDE_CATEGORIA_PRODUCTO_V AS
SELECT
    P.FIDE_PRODUCTOS_ID_PK AS 'ID DEL PRODUCTO',
    P.FIDE_PRODUCTOS_NOMBRE AS 'NOMBRE DEL PRODUCTO',
    P.FIDE_PRODUCTOS_DESCRIPCION AS 'DESCRIPCION DEL PRODUCTO',
    C.FIDE_CATEGORIAS_NOMBRE AS 'NOMBRE DE LA CATEOGORIA',
    C.FIDE_CATEGORIAS_DESCRIPCION AS 'DESCRIPCION DE LA CATEOGORIA'
FROM FIDE_PRODUCTOS_TB P
INNER JOIN FIDE_CATEGORIAS_TB C ON P.FIDE_CATEGORIAS_ID_FK = C.FIDE_CATEGORIAS_ID_PK
GO

SELECT * FROM FIDE_CATEGORIA_PRODUCTO_V;



---VER LA PERSONA RELACIONADA CON UNA BITACORA 
GO
CREATE VIEW FIDE_USUARIO_EN_BITACORA_V AS
SELECT
    B.FIDE_USUARIOS_ID_FK AS 'ID DEL USUARIO',
    B.FIDE_BITACORA_ID_PK AS 'ID DE LA BITACORA',
    B.FIDE_BITACORA_FECHA AS 'FECHA DE LA BITACORA',
    U.FIDE_USUARIOS_NOMBRE AS 'NOMBRE',
    U.FIDE_USUARIOS_APELLIDO1 AS 'PRIMER APELLIDO',
    U.FIDE_USUARIOS_APELLIDO2 AS 'SEGUNDO APELLIDO',
    U.FIDE_USUARIOS_RED AS 'NOMBRE EN LA RED'
FROM FIDE_BITACORA_TB B
INNER JOIN FIDE_USUARIOS_TB U ON B.FIDE_USUARIOS_ID_FK = U.FIDE_USUARIOS_ID_PK
GO


SELECT * FROM FIDE_USUARIO_EN_BITACORA_V;



---VER SI UNA EMPRESA ESTA ACTIVA 
GO
CREATE VIEW FIDE_ESTADO_EMPRESA_V AS
SELECT
    E.FIDE_EMPRESA_CEDULA_PK AS 'CEDULA JURIDICA',
    E.FIDE_EMPRESA_NOMBRE AS 'NOMBRE DE LA EMPRESA',
    S.FIDE_ESTADO_TIPO AS 'ESTADO DE LA EMPRESA'
FROM FIDE_EMPRESA_TB E
INNER JOIN FIDE_ESTADO_TB S ON E.FIDE_ESTADO_ID_FK = S.FIDE_ESTADO_ID_PK
GO

SELECT * FROM FIDE_ESTADO_EMPRESA_V;

---VER INFORMACION DE VENTA CON EMPRESA 
GO
CREATE VIEW FIDE_EMPRESA_VENTA_V AS
SELECT
    V.FIDE_VENTAS_ID_PK AS 'ID DE LA VENTA',
    V.FIDE_VENTAS_FECHA AS 'FECHA',
    E.FIDE_EMPRESA_NOMBRE AS 'EMPRESA'
FROM FIDE_VENTAS_TB V
INNER JOIN FIDE_EMPRESA_TB E ON V.FIDE_EMPRESA_CEDULA_FK = E.FIDE_EMPRESA_CEDULA_PK
GO
SELECT * FROM FIDE_EMPRESA_VENTA_V;


---VER EL ROL DE UN USUARIO 
GO
CREATE VIEW FIDE_USUARIO_ROL_V AS
SELECT
    U.FIDE_USUARIOS_ID_PK AS 'ID DEL USUARIO',
    U.FIDE_USUARIOS_NOMBRE AS 'NOMBRE',
    U.FIDE_USUARIOS_APELLIDO1 AS 'PRIMER APELLIDO',
    U.FIDE_USUARIOS_APELLIDO2 AS 'SEGUNDO APELLIDO',
    R.FIDE_ROLES_NOMBRE AS 'TIPO DEL ROL'
FROM FIDE_USUARIOS_TB U
INNER JOIN FIDE_ROLES_TB R ON U.FIDE_ROLES_ID_FK = R.FIDE_ROLES_ID_PK
GO

SELECT * FROM FIDE_USUARIO_ROL_V;


---VER DETTALE DE VENTA CON PRODUCTOS 
GO
CREATE VIEW FIDE_DETALLE_VENTA_PRODUCTO_V AS
SELECT
    D.FIDE_DETALLE_VENTA_ID_PK AS 'ID DEL DETALLE',
    D.FIDE_VENTAS_ID_FK AS 'ID DE LA VENTA',
    D.FIDE_DETALLE_VENTA_CANTIDAD AS 'CANTIDAD',
    P.FIDE_PRODUCTOS_NOMBRE AS 'PRODUCTO VENDIDO',
    E.FIDE_ESTADO_TIPO AS 'ESTADO DEL DETALLE'
FROM FIDE_DETALLE_VENTA_TB D
INNER JOIN FIDE_PRODUCTOS_TB P ON D.FIDE_PRODUCTOS_ID_FK = P.FIDE_PRODUCTOS_ID_PK
INNER JOIN FIDE_ESTADO_TB E ON D.FIDE_ESTADO_ID_FK = E.FIDE_ESTADO_ID_PK
GO

SELECT * FROM FIDE_DETALLE_VENTA_PRODUCTO_V;


---ER INFOMRACION DE VENTA POR UN USUARIO 
GO
CREATE VIEW FIDE_USUARIO_VENTA_V AS
SELECT
    V.FIDE_VENTAS_ID_PK AS 'ID DE LA VENTA',
    V.FIDE_VENTAS_FECHA AS 'FECHA',
    U.FIDE_USUARIOS_NOMBRE AS 'NOMBRE DEL USUARIO',
    U.FIDE_USUARIOS_APELLIDO1 AS 'PRIMER APELLIDO',
    U.FIDE_USUARIOS_APELLIDO2 AS 'SEGUNDO APELLIDO'
FROM FIDE_VENTAS_TB V
INNER JOIN FIDE_USUARIOS_TB U ON V.FIDE_USUARIOS_ID_FK = U.FIDE_USUARIOS_ID_PK
GO

SELECT * FROM FIDE_USUARIO_VENTA_V;


---VER EL TIPO DE MOVIMIENTO DE UN MOVIMIENTO 
GO
CREATE VIEW FIDE_DETALLE_TIPO_MOVIMIENTO_V AS
SELECT
    M.FIDE_MOVIMIENTOS_ID_PK AS 'ID DEL MOVIMIENTO',
    M.FIDE_PRODUCTOS_ID_FK AS 'ID DEL PRODUCTO',
    M.FIDE_MOVIMIENTOS_DETALLES AS 'DETALLES DEL MOVIMIENTO',
    T.FIDE_TIPOS_MOVIMIENTO_NOMBRE AS 'TIPO DEL MOVIMIENTO'
FROM FIDE_MOVIMIENTOS_INVENTARIO_TB M
INNER JOIN FIDE_TIPOS_MOVIMIENTO_TB T ON M.FIDE_TIPOS_MOVIMIENTO_ID_FK = T.FIDE_TIPOS_MOVIMIENTO_ID_PK
GO

SELECT * FROM FIDE_DETALLE_TIPO_MOVIMIENTO_V;
